### ISSUE TITLE
Refactor Unmarshaling

### ISSUE THREAD

**Issue by wwwdata** [manyminds/api2go#111]
Unmarshaling currently unmarshals into a `map[string]interfaface{}`. 
This is not the most elegant solution, because we have to do some magic about type casting and calling the `json.Unmarshaler` interface. 

We should try to directly scan into the target struct type to avoid all this trouble.

**Comment by pmccarren** [comment]
Do you see support for unmarshmaling 'Compound Documents'? For example, if you are using the jsonapi marshaler from a client's perspective, an api server can return compound documents. (http://jsonapi.org/format/#document-structure-compound-documents)

**Comment by wwwdata** [comment]
Hm. Api2go is currently only for the server. But it's a very good idea I think. So you are having a jsonapi server and want to use a golang program to acces it, right?
It's definitely possible to implement that too. But I would do it after we refactored the current functionality. Maybe we should open a separate ticket for this feature to use api2go as a client.

**Comment by pmccarren** [comment]
Yeah that is correct -- a jsonapi server, and looking to have a golang program access it. Would you like me to open a separate ticket?

**Comment by wwwdata** [comment]
yes. Do it please :) I like the idea
