### ISSUE TITLE
Make marshalError() and marshalHTTPError() public

### ISSUE THREAD

**Issue by pengux** [manyminds/api2go#117]
When creating custom endpoint handlers, it is necessary to produce custom errors too. So it would be nice if marshalError and marshalHTTPError are public so it can be used by the consuming package. Maybe those methods should be moved to the jsonapi package too?

**Comment by wwwdata** [comment]
hm, I think you're right, this makes sense. What do you think @sharpner ?

**Comment by sharpner** [comment]
I like the idea of opening error marshalling to the public API. But the current implementation is very http specific. Maybe we can move the marshalHTTPError to api2go.MarshalHTTPError and the marshalError to jsonapi.MarshalError?
