### ISSUE TITLE
Program panics when using multiple references in compound document

### ISSUE THREAD

**Issue by tanmayambre** [manyminds/api2go#125]
I have written a test project to use.
Please find the code at https://github.com/tanmayambre/testapi2go.git

As an example document author has two refernced documents. "blog" and "book" 
I implmented functions for jsonapi.EditToManyRelations interface 
If I implement DeleteToManyIDs(name string, IDs []string) error the program compiles but running it causes it to panic. 
The stacktrace is at the end of the description  and also in the test project.

If I use just single document as a reference it works completely fine. 
If I remove DeleteToManyIDs function keeping the tworefernces in document it doesn't throw a panic. 

Please help I cant find if there is an obvious mistake if there is any.

```
Stacktrace.

panic: a handle is already registered for path ''/v1/authors/:id/links/:name'

goroutine 1 [running]:


github.com/julienschmidt/httprouter.(*node).addRoute(0xc208046960, 0xc2080a3756, 0x5, 0xc2080a3720)
	/home/bellrock1/gocode/src/github.com/julienschmidt/httprouter/tree.go:190 +0xc7d
github.com/julienschmidt/httprouter.(*Router).Handle(0xc2080cc150, 0x73b0f0, 0x4, 0xc2080a3740, 0x1b, 0xc2080a3720)
	/home/bellrock1/gocode/src/github.com/julienschmidt/httprouter/router.go:229 +0x1fd
github.com/julienschmidt/httprouter.(*Router).POST(0xc2080cc150, 0xc2080a3740, 0x1b, 0xc2080a3720)
	/home/bellrock1/gocode/src/github.com/julienschmidt/httprouter/router.go:188 +0x59
github.com/manyminds/api2go.(*API).addResource(0xc208046dc0, 0x7fb3672faea8, 0xc208058240, 0x7fb3672fae68, 0xc208038258, 0xc20807de30)
	/home/bellrock1/gocode/src/github.com/manyminds/api2go/api.go:329 +0xe42
github.com/manyminds/api2go.(*API).AddResource(0xc208046dc0, 0x7fb3672faea8, 0xc208058240, 0x7fb3672fae68, 0xc208038258)
	/home/bellrock1/gocode/src/github.com/manyminds/api2go/api.go:373 +0x50
main.main()
	/home/bellrock1/gocode/src/github.com/testapi2go/main.go:15 +0x113
```

**Comment by sharpner** [comment]
Thanks. We'll look into it!

**Comment by wwwdata** [comment]
i am currently looking into it, it seems we have a bug in our router setup and a route setup gets called multiple times. I am fixing it :)

**Comment by sharpner** [comment]
:+1: thx @wwwdata and @tanmayambre

**Comment by tanmayambre** [comment]
Thanks for prompt response.
