### ISSUE TITLE
Client-Generated-Id are allowed by the json-api 1.0, not supported in api2go.

### ISSUE THREAD

**Issue by tanmayambre** [manyminds/api2go#127]
If I use id  (client-generated) for a document during POST request I get a 403 Forbidden error.

As per the spec I interpret that it should be left to the client to generate the id and should be allowed.  Is there a flag which can allow me to set client generated id as it is useful in certain use cases for my server using api2go.

```
Client-Generated IDs

A server MAY accept a client-generated ID along with a request to create a resource. An ID MUST be specified with an id key, the value of which MUST be a universally unique identifier. The client SHOULD use a properly generated and formatted UUID as described in RFC 4122 [RFC4122].

A server MUST return 403 Forbidden in response to an unsupported request to create a resource with a client-generated ID.
```

**Comment by wwwdata** [comment]
hi, no that is not currently supported but it shouldn't  be that difficult to add this feature. We can do this next :)

How to configure that client generated ids are allowed? What do you think would be best?

**Comment by tanmayambre** [comment]
The best way according to me is let the implementation of the callbacks decide whether to use client-generated-id  or not. i.e. remove check for client-generated id from api2go. 

As it is upto the callback to generate the id, then logically the callback to create method should decide whether  to accept client generated id or reject and thus return 403

Cheers.

**Comment by wwwdata** [comment]
With callback you mean the `Create` Method of a resource, right? So we just remove the client generated id check and it's the users responsibility to deal with it in the `Create` method ?

**Comment by tanmayambre** [comment]
Yes thats correct

**Comment by wwwdata** [comment]
ok that's easy we just have to remove some lines here: https://github.com/manyminds/api2go/blob/master/api.go#L622

```go
checkID, ok := newObj.(jsonapi.MarshalIdentifier)
	if ok {
		if checkID.GetID() != "" {
			err := Error{
				Status: string(http.StatusForbidden),
				Title:  "Forbidden",
				Detail: "Client generated IDs are not supported.",
			}

			return respondWith(err, info, http.StatusForbidden, w, r, res.marshalers)
		}
	}
```

**Comment by wwwdata** [comment]
what we have to do here is to check whether it is a real `UUID` which is a `MUST` in the spec

**Comment by tanmayambre** [comment]
From the spec . 

http://jsonapi.org/format/#crud

NOTE: In some use-cases, such as importing data from another source, it may be possible to use something other than a UUID that is still guaranteed to be globally unique. **Do not use anything other than a UUID unless you are 100% confident** that the strategy you are using indeed generates globally unique identifiers.

**Comment by wwwdata** [comment]
hmm ok, so it's optional and we don't need a check. Ok. The user of api2go has to check the correct format of the id then.

**Comment by tanmayambre** [comment]
Yes, thats how I interpret it.
