### ISSUE TITLE
Release milestones.

### ISSUE THREAD

**Issue by ben-crowhurst** [manyminds/api2go#130]
We've been using api2go for six months in a commercial (start-up) environment; and various members of the team have raised issues and feedback into the project.

The latest release (RC3) was on 20th April 2015.  This release contains issues and is outdated in comparison to the JSON API specification.  Having attempted to use HEAD and found numerous issues this past week, it has become clear we should rollback, roll our own, or other.

The tip of the repository has many fixes/improvements when compared to the 3 month old RC3.

* What release process is currently in place?
* What is the timescale for a stable RC4 release?
* How do the release candidates relate to the 1.0, 2.0 Git tags?

Thanks for all the hard work and our team will continue to feedback/chip-in where and whenever we can.

**Comment by wwwdata** [comment]
Hi,
at the moment, the plan is to get version 1.0 up and running. So far most of the things for jsonapi 1.0 are working. 

if you have found any bugs, please open tickets for them, we can fix them together, to get a stable 1.0 version. You can link anything related to version 1.0 to this ticket #124

**Comment by sharpner** [comment]
And remember, your contributions are always welcome =)

**Comment by sharpner** [comment]
Since there is no further communication in this ticket I'll close it for now. 

Let us know if you have more questions simply by opening new issues :-)
