### ISSUE TITLE
crud_example.go not unmarshalling request

### ISSUE THREAD

**Issue by wkrause13** [manyminds/api2go#131]
I have a fresh install of the api2go library, but I am running into issues with the example code provided. Whenever I try to create a resource, the data fields are not showing up in the handlers. As you can see from the return statement below, "user-name" is blank. The same thing happens when using the "Create a chocolate with the name sweet" example curl statement. Placing a print statement for user at the beginning to the Create block returns:
{   [] [] false}

I can't tell if the framework is supposed to unmarshall the request into the User struct or if we have to explicitly use the r api2go.Request parameter. 

```
curl -X POST http://localhost:31415/v0/users -d '{"data" : [{"type" : "users" , "user-name" : "marvin"}]}'
{
    "data": {
        "attributes": {
            "id": "1",
            "user-name": ""
        },
        "id": "1",
        "relationships": {
            "sweets": {
                "data": [],
                "links": {
                    "related": "http://localhost:31415/v0/users/1/sweets",
                    "self": "http://localhost:31415/v0/users/1/relationships/sweets"
                }
            }
        },
        "type": "users"
    }
}
```

**Comment by wwwdata** [comment]
hi, thanks for finding this! It seems that we forgot to change the comments in the example. All properties now must go into an `attributes` sub-object. 

So, the correct POST request would be like:

```
curl -X POST http://localhost:31415/v0/users -d '{"data" : [{"type" : "users" , "attributes": {"user-name" : "marvin"}}]}'
{
    "data": {
        "attributes": {
            "id": "1",
            "user-name": "marvin"
        },
        "id": "1",
        "relationships": {
            "sweets": {
                "data": [],
                "links": {
                    "related": "http://localhost:31415/v0/users/1/sweets",
                    "self": "http://localhost:31415/v0/users/1/relationships/sweets"
                }
            }
        },
        "type": "users"
    }
}%
```

I will change this immediately!

**Comment by wwwdata** [comment]
I will also update the example how to only list the sweets of a user. It seems we forgot to check for the user-id in the FindAll Method of the sweets in the example too. Will include this in my commit.

**Comment by wwwdata** [comment]
short update: found a couple of things i want to improve, will probably commit tomorrow :)

**Comment by wkrause13** [comment]
Thanks for jumping on this so quickly. I found one more example command using legacy syntax. The example below uses "linkage" instead of "data"
```
curl -X POST http://localhost:31415/v0/users -d '{"data" : [{"type" : "users" , "user-name" : "marvin", "relationships": {"sweets": {"linkage": [{"type": "chocolates", "id": "1"}]}}}]}'
```
It should be this:
```
curl -X POST http://localhost:31415/v0/users -d '{"data" : [{"type" : "users" , "attributes": {"user-name" : "marvin"},"relationships": {"sweets":{"data": [{"type": "chocolates", "id": "1"}]}}}]}'

**Comment by wwwdata** [comment]
yes, i saw that too. My plan is to split t his large example file up and make everything better readable and understandable. Also the adding and removing stuff of relationships does not work. I will fix all of that :)
