### ISSUE TITLE
Errors struct missing fields or changed structure

### ISSUE THREAD

**Issue by geoffgarside** [manyminds/api2go#137]
I've only recently started looking at JSONAPI, but I think the Errors struct doesn't match whats documented at http://jsonapi.org/format/#errors

I think the `Href` might now be `links: { about: "href" }`, also the `Path` might now be `source: { pointer: "path", parameter: "something" }`.

**Comment by sharpner** [comment]
hey thanks for this ticket. You are right, we need to change this for the 1.0 Release.

**Comment by geoffgarside** [comment]
I've been looking into implementing this and I'm not sure which of these options would be better. Keep `Error` as a (mostly) flat structure adding things like `Links` and `LinksAbout` where client code would mainly set `LinksAbout` and this is wrapped into `Links.About` when marshalling. Alternatively, add just the `Links` and `Source` fields and to fill these in client code would need to set `Links = &api2go.ErrorLinks{About: "url"}`.

The second form doesn't look as nice, but as the fields have to be optional theres not really a nice way to do this. The json encoder doesn't support calling a function on a field to ask if its empty or not.

The first option, with the mostly flat structure, would look like this.
```go
type Error struct {
	ID              string       `json:"id,omitempty"`
	Links           *ErrorLinks  `json:"links,omitempty"`
	LinksAbout      string       `json:"-"`
	Status          string       `json:"status,omitempty"`
	Code            string       `json:"code,omitempty"`
	Title           string       `json:"title,omitempty"`
	Detail          string       `json:"detail,omitempty"`
	Source          *ErrorSource `json:"source,omitempty"`
	SourcePointer   string       `json:"-"`
	SourceParameter string       `json:"-"`

	// Deprecated Fields
	Href string `json:"-"` // Please use LinksAbout
	Path string `json:"-"` // Please use Source/Pointer
}
```

The second option looks like this
```go
type Error struct {
	ID              string       `json:"id,omitempty"`
	Links           *ErrorLinks  `json:"links,omitempty"`
	Status          string       `json:"status,omitempty"`
	Code            string       `json:"code,omitempty"`
	Title           string       `json:"title,omitempty"`
	Detail          string       `json:"detail,omitempty"`
	Source          *ErrorSource `json:"source,omitempty"`

	// Deprecated Fields
	Href string `json:"-"` // Please use Links/About
	Path string `json:"-"` // Please use Source/Pointer
}
```

The `ErrorLinks` and `ErrorSource` being the following

```go
type ErrorLinks struct {
	About string `json:"about,omitempty"`
}

type ErrorSource struct {
	Pointer   string `json:"pointer,omitempty"`
	Parameter string `json:"parameter,omitempty"`
}
```

When marshalling if the deprecated fields are present and the corresponding Links or Source fields are empty, then the new fields would be filled in and the deprecated fields set to empty strings.

**Comment by wwwdata** [comment]
I would suggest to delete the deprecated fields. We are not version 1.0 stable with an api that must be as it is.

And there also can be a `meta` object which is missing in your example. The meta object can be anything
> Any members MAY be specified within meta objects.

So, we need a pointer to `interface{}` for that

I prefer the second solution. What do you think @sharpner?

**Comment by sharpner** [comment]
I also prefer the second solution. 

we could make use of the https://golang.org/pkg/encoding/json/#Marshaler and https://golang.org/pkg/encoding/json/#Unmarshaler interfaces to ignore the optional types in unmarshaling and marshaling which would improve the output I think.

Awesome work btw, thank you ;)

**Comment by geoffgarside** [comment]
So this one

```go
type Error struct {
	ID     string      `json:"id,omitempty"`
	Links  ErrorLinks  `json:"links,omitempty"`
	Status string      `json:"status,omitempty"`
	Code   string      `json:"code,omitempty"`
	Title  string      `json:"title,omitempty"`
	Detail string      `json:"detail,omitempty"`
	Source ErrorSource `json:"source,omitempty"`
	Meta   interface{} `json:"meta,omitempty"`
}

type ErrorLinks struct {
    About string `json:"about,omitempty"`
}

type ErrorSource struct {
    Pointer   string `json:"pointer,omitempty"`
    Parameter string `json:"parameter,omitempty"`
}
```

and implement the Marshaler/Unmarshaler interfaces to omit the empty links and source fields? I don't know if we'd need the Unmarshaler interface as decoding into the above works fine with and without any link/source data being present. For the sake of completeness though it could be done.

I'll have a go at this today, I've found that the Ember.js JSONAPIAdapter needs the "source/pointer" attribute in order to capture errors correctly.

**Comment by wwwdata** [comment]
:+1:

**Comment by wwwdata** [comment]
PR #139 is merged, I am closing this
