### ISSUE TITLE
Non-json error responses for invalid path

### ISSUE THREAD

**Issue by tanmayambre** [manyminds/api2go#143]
if I make a request for eg. 
curl -X PATCH http://lcoalhost:3000/sweets 

I get a 405 Method not Allowed which is correct but error object is "Content-Type: text/plain; charset=utf-8" body "Method Not Allowed"

I think any error or responses by the server implmented with api2go should return a jsonapi error object.

**Comment by sharpner** [comment]
thx, we'll look into it ;)
