### ISSUE TITLE
Unmarshal doesn't respect json struct tag

### ISSUE THREAD

**Issue by dustinsmith1024** [manyminds/api2go#154]
When unmarshalling a reference ID it doesn't use the normal JSON tag properly.

```go
type Loan struct {
	ID             int                 `json:"id" db:"id" `
	CustomerID     int         `json:"customerId"  db:"customer_id"`
}
```

If I send in customerId with lowercase Id:

```json
{
  "data": {
    "attributes": {
      "customerId": 1
    }
  }
}
```

I get this error: `expected struct Loan to have field CustomerId`

Setting the `jsonapi="name=customerId"` doesn't actually help either.

The solution appears to be just use capital `customerID` in my JSON, which is fine for me. It just wasn't obvious to me that's how it worked.

**Comment by sharpner** [comment]
Thanks for the report! I'm on it ;)

**Comment by wwwdata** [comment]
found the bug, PR should be merged soon

**Comment by wwwdata** [comment]
#155 was merged, your bug should be fixed with that.
