### ISSUE TITLE
Can't install (error with notAllowedHandler)

### ISSUE THREAD

**Issue by trapias** [manyminds/api2go#157]
Hello,
I tried installing the library both via "go get" and by installing the sources downloading version 0.3, but including it immediately gives me the error:

	# github.com/manyminds/api2go
	../../../manyminds/api2go/api_public.go:78: cannot use notAllowedHandler literal (type notAllowedHandler) as type http.HandlerFunc in assignment

Commenting out line 78 seems to fix the problem. Will now try to convert my handlers to api2go!

**Comment by wwwdata** [comment]
do you maybe have an outdated version of julienschmidt's httprouter?

**Comment by trapias** [comment]
@wwwdata OMG yes that was it, sorry to bother! :blush:

**Comment by wwwdata** [comment]
no problem :smile:
