### ISSUE TITLE
Convert existing httprouter and middleware handlers to api2go: suggestions?

### ISSUE THREAD

**Issue by trapias** [manyminds/api2go#158]
Hello,
this is not an issue, don't mean to bother anybody but would like to have some help if possible.

I'm developing an API server that uses https://github.com/julienschmidt/httprouter to manage handlers, in conjunction with https://github.com/justinas/alice to easily chain handlers and https://github.com/gorilla/context to handle context variables. Since api2go also uses httprouter, I think converting my code to use it should be possible and not overkilling.  But I'm new to Go too, and hardly can see some details atm :blush: , like how to continue using my middleware handlers.

I now setup my handlers like:

	commonHandlers := alice.New(context.ClearHandler, applicationcontext.CORSHandler, applicationcontext.ConfigHandler, applicationcontext.JWTHandler, applicationcontext.LoggingHandler)

	router.GET("/api/1/users", applicationcontext.WrapHandler(commonHandlers.ThenFunc(apiserver.GetUsers)))

where my WrapHandler() func wraps "normal" http handlers so that they can be used as methods but "passing through" the chain of handlers via next.ServeHTTP(w, r) calls:

	func WrapHandler(h http.Handler) httprouter.Handle {
		return func(w http.ResponseWriter, r *http.Request, ps httprouter.Params) {
			context.Set(r, "params", ps)
			h.ServeHTTP(w, r)
		}
	}

	func ConfigHandler(next http.Handler) http.Handler {
	fn := func(w http.ResponseWriter, r *http.Request) {

			var cfg configuration.Configuration
			cfg = configuration.ReadConfig()
			context.Set(r, "cfg", cfg)

			next.ServeHTTP(w, r)
		}
		return http.HandlerFunc(fn)
	}

	func GetUsers(w http.ResponseWriter, r *http.Request) {
		cfg := context.Get(r, "cfg").(configuration.Configuration)
		// ....
		fmt.Fprintf(w, "{\"users\": %v}", string(sData))
	}

Since api2go handles resources generating its own handlers, how could I convert my middleware handlers so that they can be used with api2go?

**Comment by wwwdata** [comment]
Hi, you can get the http router if you like via http://godoc.org/github.com/manyminds/api2go#API.Router

```go
func (api *API) Router() *httprouter.Router
```

you should be able to register any other routes you like with that. 

I have never used alice nor context but if you need more help I will look into them too and see if I can do an example or sth.

**Comment by trapias** [comment]
@wwwdata yes I can get the router and add other routes, indeed I can have all of my old code working by doing so. 

I'm now trying to understand how I can adapt the "WrapHandler" I was previously using. Starting from the example I'm replicating the "users" resource/model/route and trying to add what I need. I see I could access the http.Request object in my resource methods, e.g.:

	// FindAll to satisfy api2go data source interface
	func (s UserResource) FindAll(r api2go.Request) (api2go.Responder, error) {
		var result []model.User
		userid := context.Get(r.PlainRequest, "userid").(string)
		// ...
	} 

I just need to understand how to put values in context :grimacing:. Would like to reuse my handlers, e.g. if I could use my JWTHandler I'd have authentication ready, but I'm trying hard myself to see if I can understand how!

Thank you  Ben.

Regards,
al.

**Comment by wwwdata** [comment]
So you are chaining some http handlers together right? And in a previous handler, something is set via `context.Set` into the request object? This should work. We are just passing through the reference to the original `*http.Request` struct. 

I am doing something similar in a project. I was using a normal go mux for that, but with alice it should work like this (i did not test it, this is just written down from reading docs). Alice looks cool, way nicer and better readable syntax :smile: 

```go
// this is the signature for an alice middleware
func securityWrapper(handleIn http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// do stuff like setting context vars
		context.Set(r, "key", "value")
	}
}

// then wrap it before api2go handler. I did use a normal go mux for that, but with alice
// it should be easy too since it does exactly the same, chaining http.Handlers together,
// should be like this:
alice.New(securityWrapper).Then(api2goInstance.Handler())
```

**Comment by trapias** [comment]
@wwwdata oh yes, it works perfectly!!! :grinning: 

Alice handlers are like my ConfigHandler above (so simple to chain indeed, I too like the simple syntax), but it works just like you tell - very happy!

I now just have to understand how to extract a route from the chain of handlers. Until now I was using two different chains, one with all handlers and one without the JWT authentication handler, only used for the /login route - needed to obtain an authorization token, so it cannot of course be itself protected by authentication:

	commonHandlers := alice.New(context.ClearHandler, applicationcontext.CORSHandler, applicationcontext.ConfigHandler, applicationcontext.JWTHandler, applicationcontext.LoggingHandler) //, applicationcontext.RecoverHandler)
	authHandlers := alice.New(context.ClearHandler, applicationcontext.CORSHandler, applicationcontext.ConfigHandler, applicationcontext.LoggingHandler)  

	// unprotected
	router.POST("/api/1/login", applicationcontext.WrapHandler(authHandlers.ThenFunc(applicationcontext.AuthHandler)))

	// protected
	router.GET("/api/1/users", applicationcontext.WrapHandler(commonHandlers.ThenFunc(apiserver.GetUsers)))
	
I now modified my code like this:

	api := api2go.NewAPIWithMarshalers("api/1", "https://"+cfg.Host+":"+cfg.Port, marshalers)
	
	userStorage := storage.NewUserStorage()
	api.AddResource(model.User{}, resource.UserResource{UserStorage: userStorage})

	// previous version
	// router := applicationcontext.NewRouter()

	// current version: get the router from api2go instance
	router := api.Handler().(*httprouter.Router)

	err := http.ListenAndServeTLS(cfg.Host+":"+cfg.Port, "cert.pem", "key.pem", commonHandlers.Then(api.Handler()))

	// previous version, using router
	// err := http.ListenAndServeTLS(cfg.Host+":"+cfg.Port, "cert.pem", "key.pem", router)

The problem is now all routes go through commonHandlers, thus the authentication handler is called also for the login route. Maybe I just can check within it (the authentication handler), and bypass all checks if the route is /login. No better idea for now.

Thank you so much anyway, you made my day - I'll definitely go on with api2go! :grinning: Owe you :beers: !!!

**Comment by wwwdata** [comment]
Ah ok, now I see the problem. Yes indeed if you are using our internal http router instance, register a new route on it and then chain it, it would always call everything in your chain, right? So you need something before all of that. I would recommend to use a simple mux. A mux just goes through all registered routes in order (very stupid). So you would register custom routes first, and then a catchall for the rest. Here is an example how I am doing it too:

```go
mux := http.NewServerMux()
mux.Handle("/api/v1/login", applicationcontext.WrapHandler(authHandlers.ThenFunc(applicationcontext.AuthHandler))

api := api2go.NewAPIWithMarshalers("api/1", "https://"+cfg.Host+":"+cfg.Port, marshalers)

userStorage := storage.NewUserStorage()
api.AddResource(model.User{}, resource.UserResource{UserStorage: userStorage})

// catchall for the rest of api2go routes that need another alice chain
mux.Handle("/", commonHandlers.Then(api.Handler()))

err := http.ListenAndServeTLS(cfg.Host+":"+cfg.Port, "cert.pem", "key.pem", mux)
```

**Comment by trapias** [comment]
@wwwdata Ben, don't know how to thank you enough! :+1: :beers: :beers: :beers: 

Exactly what I needed. I just had to get the wrapper function out:

	mux := http.NewServeMux()
	mux.Handle("/api/1/login", authHandlers.ThenFunc(applicationcontext.AuthHandler))

because the AuthHandler is no more handled by httprouter, and it works perfectly.

Thanks very, very much!!!

**Comment by wwwdata** [comment]
Glad I could help you. don't forget to check if the request type is `POST` in the authentication/login handler because the mux just checks the url and not the type.

**Comment by trapias** [comment]
@wwwdata yep, I'm looking into this right now. Thanks again!

**Comment by trapias** [comment]
@wwwdata Ben, just a question if you can: do you usually also serve static content, say some HTML or a frontend to your api server, with a ServerMux?

For developing purposes I was using:

	router.ServeFiles("/app/*filepath", http.Dir("../frontend"))

to serve my frontend, but this cannot work anymore due to the router being in the chain of handlers (requires authentication). It's probably possible to replicate the "*filepath" behavior with a mux, is this the way you do it - if you do it?

Thank you,
al.

**Comment by wwwdata** [comment]
yes, you can do it with a mux. You can do it like I described here in #158 but instead of a login page, you serve static content.

For that purpose, just create a second httprouter and only use that for file serving, then use the catchall for the rest (api2go)

**Comment by trapias** [comment]
@wwwdata thanks Ben, will try again with this later.
