### ISSUE TITLE
How to set total number of records for pagination links generation

### ISSUE THREAD

**Issue by trapias** [manyminds/api2go#160]
Hello,
should I set the storage idCount property to the total number of records in order to correctly generate pagination links?

I'm not getting pagination links, or getting unexpected values. Given a "users" table with say 1000 records, and a query like (20 records per page, get first 20 records):

	[GET] "/api/1/users?page[limit]=20&page[offset]=0

I'd expect to get links like:

	next: "/api/1/users?page[limit]=20&page[offset]=1
	last: "/api/1/users?page[limit]=20&page[offset]=50

I'm trying to set the resource storage idCount value to the total number of records in table, say 1000, like this:

	func NewUserStorage() *UserStorage {
		totalRecords := GetNumerOfUsersFromDb()
		log.Debugf("Users totalrecords: %v", totalRecords) // 1000
		cs := UserStorage{make(map[string]*model.User), totalRecords}
		return &cs
	}

Is it not supposed to work this way?
Thanks for any help,

al.

**Comment by wwwdata** [comment]
with the offset pattern the next batch would start with offset 20 if you request 20 items on the first page. If you want real pages, use the other pagination query parameters: `page[number]`and `page[size]`

**Comment by trapias** [comment]
@wwwdata yep my fault, links are actually generated right in all cases once I provide the total number of records in s.idCount. Just I don't need to make the map the same large of course :flushed: 

Thanks Ben.
