### ISSUE TITLE
Question about storage

### ISSUE THREAD

**Issue by trapias** [manyminds/api2go#161]
I'm facing what likes to be a "caching" problem in my resource classes: I'd like to understand if I miss something or if this is the right way to solve the problem.

What I mean is, given an User resource like in the CRUD example but linked to a database, I see that if I call the FindAll() method to get a list of users, then Delete() one of them and again call FindAll(), I still see the deleted user in list.

To remove it, I now force a new storage instance to be created in FindAll before calling storage:

	s.UserStorage = storage.NewUserStorage()
	users, err := s.UserStorage.GetAll( ....)

The storage implementation appears to be correct, and the same for db procedures (I see the same problem on different resources): am I doing something wrong or is this normal? Where to look for errors, if it's my implementation's fault?

Thank you,
al.

**Comment by wwwdata** [comment]
well, we do not secret caching. We are talking about your implementation here and not a problem with our example project, right?

Since I do not know your own code, I don't know what you are doing wrong. Are you sure that your own database modules/structs are not caching? Are you connected to a database? Which one are you using? And what driver for the database?

**Comment by sharpner** [comment]
It would be awesome if you could provide code if you're are running into issues. 
Additionally, if you think it is a bug in api2go you can always write a failing test!

That way we can provide better and faster input :)

**Comment by trapias** [comment]
@wwwdata @sharpner I actually don't know if this could be a bug, probably not... but I'm failing to understand what I'm doing wrong :flushed: 

I have a postgres db, using github.com/lib/pq to talk with it. If I debug my storage functions I see data from database is what expected, but then a "cached" list is returned to the api caller, as told above.
Here are relevant portions of my code:

	/*
		User model
	*/
	type User struct {
		ID          string      `json:"-"`
		Name        string      `jsonapi:"name=name"`
		Login       string      `jsonapi:"name=login"`
		Email       null.String `jsonapi:"name=email"`
		DisplayName null.String `jsonapi:"name=display-name"`
		Preferences null.String `jsonapi:"name=preferences"`
		Password    string      `json:"-"`
	}

	// GetID to satisfy jsonapi.MarshalIdentifier interface
	func (u User) GetID() string {
		return u.ID
	}

	// SetID to satisfy jsonapi.UnmarshalIdentifier interface
	func (u *User) SetID(id string) error {
		u.ID = id
		return nil
	}


	/*
		UserResource
	*/
	type UserResource struct {
		UserStorage *storage.UserStorage
	}

	func (s UserResource) FindAll(r api2go.Request) (api2go.Responder, error) {
		var result []model.User
		var (
			limit              = 10 // default limit
			offset             = 0
			orderby            = "login" // default orderby
			querystringFilters string
		)

		cfg := context.Get(r.PlainRequest, "cfg").(configuration.Configuration)
		db := database.GetDB(cfg)
		userid := context.Get(r.PlainRequest, "userid").(string)

		perr := apiserver.ParseQueryStringParams(r.PlainRequest, &limit, &offset, &orderby, &querystringFilters)
		if perr != nil {
			log.Error(perr)
			return &Response{}, perr
		}

		// fix to avoid the "caching" problem: without this line I get unexpected results
		s.UserStorage = storage.NewUserStorage()

		users, err := s.UserStorage.GetAll(db, userid, limit, offset, orderby, querystringFilters)
		if err != nil {
			return &Response{}, err
		}

		// use keys to reorder map
		var keys []int
		for k := range users {
			// log.Printf("K: %v", k)
			i, err := strconv.ParseInt(k, 10, 64)
			if err != nil {
				return &Response{}, err
			}

			keys = append(keys, int(i))
		}
		sort.Ints(keys)

		for i := 0; i < len(users); i++ {
			result = append(result, *users[strconv.FormatInt(int64(keys[i]), 10)])
		}

		return &Response{Res: result}, nil
	}


	func (s UserResource) Delete(id string, r api2go.Request) (api2go.Responder, error) {
		cfg := context.Get(r.PlainRequest, "cfg").(configuration.Configuration)
		db := database.GetDB(cfg)
		userid := context.Get(r.PlainRequest, "userid").(string)

		err := s.UserStorage.Delete(db, userid, id)
		return &Response{Code: http.StatusNoContent}, err
	}

	/*
	 	UserStorage
	*/
	func NewUserStorage() *UserStorage {
		return &UserStorage{make(map[string]*model.User), 1}
	}

	type UserStorage struct {
		users   map[string]*model.User
		idCount int
	}

	func (s UserStorage) GetAll(db *sql.DB, userid string, limit, offset int, orderby, querystringFilters string) (map[string]*model.User, error) {

		rows, err := db.Query("SELECT * from getusers($1,$2,$3,$4)", limit, offset, orderby, querystringFilters)
		if err != nil {
			log.Error(err)
			return nil, err
		}

		n := 0

		defer rows.Close()
		for rows.Next() {
			n++

			var u model.User
			err := rows.Scan(&u.ID, &u.Name, &u.Login, &u.Email, &u.DisplayName, &u.Preferences)
			if err != nil {
				log.Error(err)
				return nil, err
			}
			// using a counter to set keys, 'cause my IDs are UUIDs
			sn := fmt.Sprintf("%v", n)
			s.users[sn] = &u
		}

		totalRecords, err := apiserver.GetTotalRecords(db, "users")
		if err != nil {
			log.Errorf("Cannot get number of records: %v", err)
		}
		s.idCount = totalRecords

		return s.users, nil
	}


	func (s *UserStorage) Delete(db *sql.DB, userid string, id string) error {

		var uuid string
		err := db.QueryRow("SELECT deleteuser($1)", id).Scan(&uuid)
		if err != nil {
			log.Error(err)
			return err
		}
		log.Debugf("Deleted user %v", id)

		delete(s.users, id)

		return nil
	}


Can you see what I'm doing wrong here?
Thanks for any help!!!

**Comment by sharpner** [comment]
is this still relevant? I'm sorry but I don't think anyone is currently debugging the code for you :) If you have a specific question about api2go feel free to ask, but since this problem is most likely within your code, it's better to ask on stackoverflow or somewhere else.  :-)

**Comment by trapias** [comment]
@sharpner :) the intention was not to ask anybody to debug my code, I thought it could be somewhat a "more-real-world" example - I mean it's just the CRUD example extended to work with a database, basically, but I agree if something is wrong that's not sure api2go!

**Comment by sharpner** [comment]
Yeah i know :-)
