### ISSUE TITLE
Unmarshaling int based `enum` types fails

### ISSUE THREAD

**Issue by christianklotz** [manyminds/api2go#167]
#### Summary

Adding a enum-style field of type int to a struct breaks unmarshal. This is tricky since it's common to have human readable enum value representations of type `string`. In the following example I've chosen to add a field `Status` of type `PublishStatus` to the post. In JSON it would be represented either as `unpublished` or `published`.

```go
type EnumPost struct {
	ID     string `json:"-"`
	Title  string
	Status PublishStatus
}
```

The `PublishStatus` type implements `TextMarshaler`, `TextUnmarshaler` and `Stringer`.
```go
type PublishStatus int

const (
	StatusUnpublished PublishStatus = iota
	StatusPublished
)

var publishStatusValues = []string{
	StatusUnpublished: "unpublished",
	StatusPublished:   "published",
}
```
An example of the status type can be seen in [this playground](http://play.golang.org/p/pi-2JEZsMj)

#### Resulting error
```
"Could not set field 'Status'. Value 'published' had wrong type"
```
It's basically trying to set it as `Int` straight away in [jsonapi/unmarshal.go#L334](https://github.com/manyminds/api2go/blob/792d9ff930986116539ceed2bcb07bd907563242/jsonapi/unmarshal.go#L334) instead of relying on the unmarshal methods. This is obviously doomed because the value coming from JSON is of type string.

I've added a [gist with the full failing test](https://gist.github.com/christianklotz/6e0e81781e7c592f6697), too.

**Comment by wwwdata** [comment]
hm, so it will never reach the default case a few lines down in unmarshal.go that you linked. I guess we have to check for the `Unmarshaler` interface first and it should be working. I will try that out later.

**Comment by wwwdata** [comment]
hey, I opened a pull request. What I had to change was your unmarshal method. Because unmarshal receives the value as is, so in json format a string has `""` around it. I had to change that for you, and I added a marshal test, just to have one too for the enum type. Seems to work now. Please review it, then we can merge :smile:

**Comment by christianklotz** [comment]
Hey, thanks for looking into it so quickly. Just tested it and works. The only thing I wonder is whether the unmarshal method should be changed in a slightly different way.

Instead of:

```go
func (s *PublishStatus) UnmarshalText(text []byte) error {
	var label string
	json.Unmarshal(text, &label)

	for key, v := range publishStatusValues {
		if v == label {
			*s = PublishStatus(key)
			return nil
		}
	}

	return fmt.Errorf("invalid value `%s`", label)
}

func (s *PublishStatus) UnmarshalJSON(data []byte) error {
	return s.UnmarshalText(data)
}
```

… move the json relevant part to the `UnmarshalJSON` method like so:

```go
func (s *PublishStatus) UnmarshalText(text []byte) error {
	label := string(text)

	for key, v := range publishStatusValues {
		if v == label {
			*s = PublishStatus(key)
			return nil
		}
	}

	return fmt.Errorf("invalid value `%s`", label)
}

func (s *PublishStatus) UnmarshalJSON(data []byte) error {
	var text string
	if err := json.Unmarshal(data, &text); err != nil {
		return err
	}
	return s.UnmarshalText([]byte(text))
}
```

**Comment by wwwdata** [comment]
yes, you can do it like that. The only important thing for us is the `UnmarshalJSON` method since this method fulfilfs the interface. The `UnmarshalText` method doesn't matter, it's just an internal method for you.

**Comment by christianklotz** [comment]
Sounds good. Thanks again for the fix!
