### ISSUE TITLE
Support passing a Context to handlers

### ISSUE THREAD

**Issue by interlock** [manyminds/api2go#169]
Many advanced routing frameworks wrap handlers to also contain a Context implementation. Some are based on this https://godoc.org/golang.org/x/net/context and others are custom rolled.

If the community is open to it, I can submit a PR which adds this functionality. It should allow people to pass in per connection db handles, global and request configuration, logging handlers, etc.

**Comment by wwwdata** [comment]
Hi, yes why not. Go ahead implement it and make a PR :+1:

**Comment by sharpner** [comment]
would be awesome to have that, please go for it ! :)
