### ISSUE TITLE
jsonapi internal ignore tag

### ISSUE THREAD

**Issue by wwwdata** [manyminds/api2go#171]
When working with different database drivers, that rely on json themselves, it is possible that I need to deserialize fields, that I do not want to serialize via api2go. In that case, it was necessary to use the `json:"-"` ignore tag. This is a problem because i want these fields to be serialized/deserialized when talking to my database via json. 

Therefore, it would be a nice feature to have a `jsonapi:"-"` ignore tag, that only ignores if serialized via our jsonapi marshaler.

Of course it is always a possibility to use a different struct to talk to the database, but it's unnecessary overhead if it is not needed and everything can be achieved with one struct.

**Comment by sharpner** [comment]
imho it should only be ```jsonapi:"-"```  and not ```json:"-"```.... I think it's a bug.

**Comment by wwwdata** [comment]
no it's not a bug. our jsonapi tag allows the renaming at the moment. But yes it is weird and for api2go stuff we should always use the jsonapi tag, so it does not interfere with the json tag.

**Comment by sharpner** [comment]
so lets ignore the json tag and use the jsonapi tag!
