### ISSUE TITLE
Case sensitivity with respect to query parameters.

### ISSUE THREAD

**Issue by ben-crowhurst** [manyminds/api2go#176]
Is it possible to ignore cAsE when processing query parameters?   I've raised the following [issue](https://github.com/json-api/json-api/issues/884) with the json-api team.

**Comment by wwwdata** [comment]
hm, currently we take the query parameters as they come in, which is case sensitive in go. Since we have our middleware chain, it should be very easy to write a middleware that just processes all the query parameters and lowercase/uppercases them.

**Comment by ben-crowhurst** [comment]
@wwwdata Thanks for response.  We've successfully implemented your stated approach,  craving a less clunky implementation.

**Comment by ben-crowhurst** [comment]
@wwwdata Thanks for response. We've successfully implemented your stated approach, craving a less clunky implementation.

**Comment by wwwdata** [comment]
@ben-crowhurst you're welcome, i am always happy to help.

If this is a common thing and more ppl want this feature, we could think about collecting some useful ready-to-use middlewares that we ship with api2go. This can also be great to serve as an example if you want to implement your own middlewares.

**Comment by ethanresnick** [comment]
> If this is a common thing and more ppl want this feature, we could think about collecting some useful ready-to-use middlewares that we ship with api2go.

If you do this, which would be awesome, please take into consideration the specification subtleties around uniformly lowercasing every parameter that comes in. See: https://github.com/json-api/json-api/issues/884#issuecomment-140696166

**Comment by wwwdata** [comment]
thanks @ethanresnick that makes a lot of sense!
