### ISSUE TITLE
build error: cannot use notAllowedHandler literal (type notAllowedHandler) as type http.HandlerFunc in assignment

### ISSUE THREAD

**Issue by hnakamur** [manyminds/api2go#177]
I got the following error when I ran `go build`.

```
$ go build
# github.com/manyminds/api2go
./api_public.go:97: cannot use notAllowedHandler literal (type notAllowedHandler) as type http.HandlerFunc in assignment
```

My environments:

```
$ git rev-parse HEAD
731d3e6219d91b5f9f4e3606ffc9d3a4e07ef817
$ (cd ../../julienschmidt/httprouter/ && git rev-parse HEAD)
8c199fb6259ffc1af525cc3ad52ee60ba8359669
$ go version
go version go1.5.1 darwin/amd64
```

How to build api2go successfully?

**Comment by sharpner** [comment]
ehm.. this looks strange. Could you update julienschmidt/httprouter to a more recent version?

**Comment by hnakamur** [comment]
Ah, my bad. I updated julienschmidt/httprouter to the latest commit https://github.com/julienschmidt/httprouter/commit/109e267447e95ad1bb48b758e40dd7453eb7b039 and confirmed `go build` ran successfully.
Sorry for bothering you.
Thanks for your support!
