### ISSUE TITLE
Server IP address with nginx proxy

### ISSUE THREAD

**Issue by trapias** [manyminds/api2go#179]
When my api server is on localhost, I get all links generated pointing to "0.0.0.0", e.g. "https://0.0.0.0:8000/api/1/users". This is not a problem if you are in a development environment, but in production I'd like to get the real server IP: this is not possible when using nginx as a proxy to the api server.

In my scenario, in production I have the api server running on a port which is not mapped outside, say localhost:8000, and nginx proxies requests to it. api2go is now generating all links using its private address, e.g.

    https://0.0.0.0:8000/api/1/

Would it be possible to let it use the X-Forwarded-For header to set the host part of links, when it's available, instead of the binded address?

**Comment by sharpner** [comment]
Have you tried using [NewAPIWithBaseURL](https://godoc.org/github.com/manyminds/api2go#NewAPIWithBaseURL) ?

**Comment by wwwdata** [comment]
yes, you can configure the url you like as @sharpner said. But in addition to that it could also be useful to use some X-Forwarded-For headers if you are in a larger more dynamic environment. So maybe this can be a nice to have new feature :)

**Comment by trapias** [comment]
@sharpner actually solved by passing a proper baseURL to "NewAPIWithMarshalers" (still using pretty content marshaler to easily debug), but agree with @wwwdata having X-Forwarded-For could be useful.
Can close this meanwhile, thank you!
