### ISSUE TITLE
api2go Oktoberfest Meetup

### ISSUE THREAD

**Issue by sharpner** [manyminds/api2go#181]
@lucas-clemente 
@wwwdata 
@mantenie 

We're planning to go to the Oktoberfest next week.

Are you guys in? What day would work for you?

**Comment by wwwdata** [comment]
I can arrange every day afternoon/evening. It's up to you. Everybody else that can come is invited too of course.

**Comment by mantenie** [comment]
:+1:

**Comment by sharpner** [comment]
of course, but I didn't wanna highlight everyone^^

**Comment by sharpner** [comment]
I can do Monday to Wednesday.

**Comment by mantenie** [comment]
Wednesday?

**Comment by sharpner** [comment]
Sounds good. What time?

**Comment by mantenie** [comment]
11.30?

**Comment by wwwdata** [comment]
i will only go at the evenings, so 1700+

**Comment by lucas-clemente** [comment]
Sorry, I'm pretty busy with writing my thesis and can't make it. Have fun!

**Comment by mantenie** [comment]
Party! :-)

**Comment by wwwdata** [comment]
![image](https://cloud.githubusercontent.com/assets/818880/10205327/e0f104b0-67c0-11e5-8819-748b470d016e.jpeg)

**Comment by mantenie** [comment]
Great!
