### ISSUE TITLE
Sparse Fieldsets example

### ISSUE THREAD

**Issue by hnakamur** [manyminds/api2go#183]
I noticed Sparse Fieldsets are mentioned at https://github.com/manyminds/api2go#query-params
However I don't understand how I actually do it.
Could you add the Sparse Fieldsets support to the example?
Thanks!

**Comment by wwwdata** [comment]
Ok, so the query parameter is for example this like in the [jsonapi documentation](http://jsonapi.org/format/#fetching-sparse-fieldsets):

```
?include=author&fields[articles]=title,body&fields[people]=name
```

In your resource action, for example in the FindOne action, you can access the `api2go.Request` object. This contains the property `QueryParams`.

For this query string, it contain this:
```
map[include:[author] fields[articles]:[title body] fields[people]:[name]]
```

So for example:

```go
func (s UserResource) FindOne(r api2go.Request) (api2go.Responder, error) {
	fmt.Println(r.QueryParams["fields[articles]"])
```

would print an `[]string` with the values `title, body`

So you just have to check the contents of `QueryParams` by yourself and filter your results as you wish. 

I could also update the example to filter out fields, for that matter I would have to extend it because we now only have `user-name` as the only `attributes` field. But I hope this answer helps you for now :smile:

**Comment by hnakamur** [comment]
Thank you for your answer.

In https://github.com/manyminds/api2go/blob/1352d24a19b7caeeb71f475a0e443983c4b9d4eb/jsonapi/marshal.go#L207-L214
`getStructFields` take a struct, so it returns all fields which has not `jsonapi:"-"` tag.
We can not add `jsonapi:"-"` tag dynamically according to `QueryParams` value on runtime, so I think we need to filter out fields from the result of `getStructFields`.
In order to do that, I think we need to change the signature of `marshalData`.
Is this correct?

**Comment by wwwdata** [comment]
hm yes that is correct, currently we cannot just leave some fields out. What we could easily do is also introduce an `omitempty` setting, like in the original json marshaler from go. But  I don't know if you sometimes want to send empty fields, in that case, this wouldn't be a good solution.

Hm, i will think about it, what does @sharpner say about this?

**Comment by sharpner** [comment]
Nice find! I have no solid solution at the moment. 
The spec clearly states that we mustn't send more fields than requested. 
http://jsonapi.org/format/#fetching-sparse-fieldsets

**Comment by wwwdata** [comment]
hm, so maybe the cleanest solution would be to pipe the requested field list to the marshaler that then only selects specified fields. But this needs some more thinking before any good solutions

**Comment by sharpner** [comment]
imho api2go has to handle this transparently. We know the request as we know the result, we should filter out anything not requested before sending the response. What do you think?

**Comment by wwwdata** [comment]
yes, this should be very doable. Then the sparse fields could be completely ignored in the Resource Actions and api2go just marshals the fields requested by the query parameter automatically.

In addition to that it would also be possible to access the query parameters (if a user needs that) so he can perform a better database query, which does not fetch the whole object from the database, which could be useful for large objects.

**Comment by sharpner** [comment]
Sure the user can optimize how much he wants, as long as we don't marshal not requested fields into the output ;) 

@hnakamur would that work for you?

**Comment by hnakamur** [comment]
Yes, that would be great!

**Comment by interlock** [comment]
@wwwdata Thoughts on how this would be implemented? We are at point where we need to filter fields based on requested `scope` (our internal security/view on resources) and the `fields` param.

**Comment by wwwdata** [comment]
yes, I am on it, have to push my branch, PR will come soon

**Comment by interlock** [comment]
@wwwdata let me know if you need any help finishing it off. We have some cycles to spend on it.
