### ISSUE TITLE
Total record count for pagination

### ISSUE THREAD

**Issue by hnakamur** [manyminds/api2go#184]
I would like the total record count at "links.self.meta.count" or somewhere when I use pagination.
http://jsonapi.org/format/#document-links

An example:

```
  "links": {
    "self": {
      "href": "/v0/users?page[offset]=0&page[limit]=10",
      "meta": {
        "count": 22
      }
    }
  }
```

How can I achieve that?
Thanks!

**Comment by wwwdata** [comment]
do you mean when using the `PaginatedFindAll` method? So we are talking about a top-level `links` object?

This will generate these pagination links automatically for you

```json
{
  "links": {
    "first": "http://localhost:31415/v0/users?page[number]=1&page[size]=2",
    "last": "http://localhost:31415/v0/users?page[number]=5&page[size]=2",
    "next": "http://localhost:31415/v0/users?page[number]=3&page[size]=2",
    "prev": "http://localhost:31415/v0/users?page[number]=1&page[size]=2"
  },
  "data": [...]
}
```

however, like you already noticed, there is no additional meta data like the total count at the moment. We have another ticket #136 which is about setting `links` with `meta` information into the top-level document and also in the `relationships` object.

**Comment by sharpner** [comment]
But for the record, PaginatedFindAll returns a responder and the total count values. You could store the total count in this Responder result. 

The result would look something like this:
```json
curl -X GET 'http://localhost:31415/v0/users?page\[offset\]=0&page\[limit\]=2'
{
    "data": [
        {
            "attributes": {
                "user-name": "marvin"
            },
            "id": "1",
            "relationships": {
                "sweets": {
                    "data": [],
                    "links": {
                        "related": "https://localhost:31415/v0/users/1/sweets",
                        "self": "https://localhost:31415/v0/users/1/relationships/sweets"
                    }
                }
            },
            "type": "users"
        },
        {
            "attributes": {
                "user-name": "marvin"
            },
            "id": "2",
            "relationships": {
                "sweets": {
                    "data": [],
                    "links": {
                        "related": "https://localhost:31415/v0/users/2/sweets",
                        "self": "https://localhost:31415/v0/users/2/relationships/sweets"
                    }
                }
            },
            "type": "users"
        }
    ],
    "links": {
        "last": "https://localhost:31415/v0/users?page[limit]=2\u0026page[offset]=2",
        "next": "https://localhost:31415/v0/users?page[limit]=2\u0026page[offset]=2"
    },
    "meta": {
        "author": "The api2go examples crew",
        "count": 4,
        "license": "wtfpl",
        "license-url": "http://www.wtfpl.net"
    }
}
```

**Comment by hnakamur** [comment]
Thanks for comments.
Yes, I can set "count" in the toplevel "meta" by adding "count" key in `Responder.Metadata()`.
However when I read http://jsonapi.org/format/#document-links, I thought `links.self.meta.count` is preferrable.
What do you think?

**Comment by sharpner** [comment]
yeah currently there is no support for metadata in links. It will be done in #99 and is an issue for a while now. We are still arguing about the way on how to implement this.

**Comment by hnakamur** [comment]
I see. Should I close this issue since this is duplicate of #99?

**Comment by sharpner** [comment]
Sure why not! I think it will be one of the next things we do!

**Comment by hnakamur** [comment]
I'm closing this now. I'm looking forward for #99 to be implemented!
