### ISSUE TITLE
BuildApi2GoRequest function

### ISSUE THREAD

**Issue by dennisfaust** [manyminds/api2go#185]
For testing I needed an api2go request with allocated Context, Header and QueryParams. In your tests, you have a function that builds requests. I copied and modified that for my own purposes but it would be convenient to have it available for everyone. Or at least in the documentation as an example. I'd be happy to help with either.

**Comment by sharpner** [comment]
If I understand you correctly than the long term goal would be that api2go also implements client features #122. 

But of course, It would be awesome if you open a PR that extends documentation or the examples, that stuff is always useful :)

**Comment by wwwdata** [comment]
what can we do to close this ticket? What function do you mean in our tests @dennisfaust?

**Comment by dennisfaust** [comment]
This can be closed now. I was referring to the below, which I added to my test helper file and found it useful:

func buildApi2GoRequest(c api2go.APIContexter, r *http.Request) api2go.Request {
	req := api2go.Request{PlainRequest: r}
	params := make(map[string][]string)
	for key, values := range r.URL.Query() {
		params[key] = strings.Split(values[0], ",")

	}
	req.QueryParams = params
	req.Header = r.Header
	req.Context = c
	return req
}
