### ISSUE TITLE
Marshaling of struct compositions fails

### ISSUE THREAD

**Issue by christianklotz** [manyminds/api2go#187]
When I compose a struct and then marshal it using the normal JSON encoder, all fields including those inherited from the anonymous field will be direct child objects of the composed struct. Using `jsonapi` however it creates an extra node for the anonymous field and fails to generate valid JSON.

Please see the [`marshal_composition_test.go`](https://gist.github.com/christianklotz/1d01b08027d7866d49f4) and the example given below for more.

Is this intended behaviour? If so, what would be your suggestion to deal with struct compositions?

### Example
Encoding a `TaggedPost` which is composed of a `SimplePost` and an additional field `Tag` using the  default JSON encoder gives you the following result, also see http://play.golang.org/p/JobhDfJOgu for the playground.

#### Default JSON
```json
{
  "ID":"first",
  "Title":"First Post",
  "Text":"Lipsum",
  "Size":0,
  "Created":"2014-11-10T16:30:48.823Z",
  "Tag":"important"
}
```

#### JSONAPI – Expected Result

```json
{
  "data": {
    "type": "taggedPosts",
    "id": "first",
    "attributes": {
      "title": "First Post",
      "text": "Lipsum",
      "size": 0,
      "create-date": "2014-11-10T16:30:48.823Z",
      "tag": "important"
    }
  }
}
```

#### JSONAPI – Actual Result

```json
{
  "data": {
    "type": "taggedPosts",
    "attributes": {
      "tag": "important",
      "simplePost": {
        ID: "first",
        Title: "First Post",
        Text: "Lipsum",
        Internal: "",
        Size: 0,
        Created: {
          sec: 63551233848,
          nsec: 823000000,
          loc: {
            name: "UTC", 
            zone: nil, 
            tx: nil, 
            cacheStart: 0, 
            cacheEnd: 0, 
            cacheZone: nil
          },
        },
      },
    },
    "id": "first",
  }
}
```

**Comment by wwwdata** [comment]
nice catch, we never tested marshaling of structs with compositions. We should look into this and implement it.

**Comment by christianklotz** [comment]
:)

**Comment by wwwdata** [comment]
i started working on this, doing the marshal part was trivial, pushing my WIP PR soon :smile: let's see how hard unmarshaling is
