### ISSUE TITLE
Unmarshal to *time.Time fails

### ISSUE THREAD

**Issue by mantenie** [manyminds/api2go#190]
We use in our case a struct with pointer type ```*time.Time```. Marshaling to json works fine. But ```PATCH```or ```POST```of a struct with a datetime-string fails with an error like ```Could not set field 'Field-name'. Value '2015-10-04T08:54:47.569Z' had wrong type```.

**Comment by wwwdata** [comment]
can you provide a short failing test?

**Comment by wwwdata** [comment]
just for the record, if somebody finds this ticket, it is discouraged to use a pointer to `time.Time` in a struct, so we now skip the time field if it has zero value, see: https://golang.org/pkg/time/#Time

**Comment by wwwdata** [comment]
closing this because #192 was merged in.
