### ISSUE TITLE
jsonapi handling errors?

### ISSUE THREAD

**Issue by faeronsayn** [manyminds/api2go#195]
How can we marshal errors into jsonapi compatible errors?

**Comment by wwwdata** [comment]
Hi, if you are using our api functionality, just return an instance of our `HTTPError` as `error`. This will get marshalled correctly: https://godoc.org/github.com/manyminds/api2go#HTTPError
If you return any other normal go like error, then this will also be marshalled into a json api compatible error, but always with the default status code 500. 

You can create a new error with `NewHTTPError` https://godoc.org/github.com/manyminds/api2go#NewHTTPError

@faeronsayn do you think we should add this to our documentation in this chapter? https://github.com/manyminds/api2go#building-a-rest-api

**Comment by faeronsayn** [comment]
Should definitely be in the documentation. But I was wondering how we can do it without using the API functionality.

I'm simply using the `jsonapi` package and it'd be nice if there was a way to do it with just the package.

**Comment by wwwdata** [comment]
ok in that case, you can either do it yourself, because you are only using our marshal/unmarshal functionality or you can use the structs from the api package. It's your choice. I will add an example for our api users in the documentation.

**Comment by wwwdata** [comment]
our api is very flexible. We now support adapters which allows you to use our generated routes with every framework that you like. We already wrote an adapter for the popular gin framework: https://github.com/manyminds/api2go#using-api2go-with-the-gin-framework

So, if you are planning to do a normal rest api with the standard routes, this is the easy way to go.

**Comment by faeronsayn** [comment]
thanks :+1:
