### ISSUE TITLE
Unmarshaling fails with mixed case field names, e.g. ExpiryYear

### ISSUE THREAD

**Issue by christianklotz** [manyminds/api2go#197]
I came across an issue I don't really know what to make of it. If I try to run [this test](https://gist.github.com/christianklotz/ac556f4037b13fc0dcf4) I get this:

```log
panic: invalid key "exp_year" in json. Cannot be assigned to target struct "ticket"
```

Interestingly the field exists, and the error only occurs if the `ticket` struct got the `Address` relationship and the `SetID` method is implemented in the `Address` struct. What I found is that in [`getFieldByTagName`, line 316](https://github.com/manyminds/api2go/blob/master/jsonapi/unmarshal.go#L316) it find the field successfully, however the returned result assigned in [`UnmarshalInto`, line 261](https://github.com/manyminds/api2go/blob/master/jsonapi/unmarshal.go#L261) is different than the result returned from the function. As soon as I don't use named return params it started working. I'm using `go 1.5.1`.

Can you reproduce this issue?

**Comment by wwwdata** [comment]
interesting, i have run your sample and can confirm the bug. I will look into it

**Comment by christianklotz** [comment]
At some point I tried not using named return values and it worked all of a sudden which was kind of worrying. It was also quite late at that point 👻

**Comment by wwwdata** [comment]
no that can make sense, I introduced a new function that tries to find the correct field by it's name i guess something goes wrong in there. And if so, i will add some tests too to ensure that this does not happen again in the future.

**Comment by wwwdata** [comment]
yep, epic fail from me, I forgot a return.. will open a pull request. So in some edge cases, if the for loop has more entries, that was why our tests didn't get that error.

**Comment by christianklotz** [comment]
What I mean is, as soon as I returned the values in https://github.com/manyminds/api2go/blob/master/jsonapi/unmarshal.go#L316 using a traditional `return field, found` instead of named return params as currently used it worked.

**Comment by wwwdata** [comment]
yes, I understood that :smile: pushing pr....

**Comment by christianklotz** [comment]
Ah, amazing

**Comment by christianklotz** [comment]
I'll have 🍺  to celebrate!

**Comment by wwwdata** [comment]
the weird thing in  your test file is this line here

```go
DeliveryAddress   Address       `jsonapi:"name=address"`
```

you cannot embed another api2go struct and give it a name, that makes no sense :smile: 
I am trying to create a test case right now and it seems that the error strangely only occurs when this is the case, which somehow makes sense, because then i override the previously found value with not found again.. because it recursively goes through the embedded struct and finds nothing in there

**Comment by christianklotz** [comment]
Ha, well spotted. Force of habit of adding struct tags :smile:
