### ISSUE TITLE
marshal-composition bug: cannot unmarshal a struct that contains both a dasherized tag and an embedded struct

### ISSUE THREAD

**Issue by obieq** [manyminds/api2go#199]
This issue was introduced with the marshal-composition change.  In one of my libraries, I have a struct that contains both a field whose tag name is dasherized as well as an embedded struct. 

Prior to the marshal composition change, it worked fine.  After the change, it now raises an exception along the lines of 'invalid key "body-style" in json. Cannot be assigned to target struct "AutomobileResource"'.  If I remove the dash from the tag, then it's good to go.

I reproduced the issue in your package by embedding the Comment struct in the SimplePost struct like so:

https://github.com/manyminds/api2go/blob/master/jsonapi/fixtures_test.go#L68

```
type SimplePost struct {
	Comment
	ID          string `jsonapi:"-"`
	Title, Text string
	Internal    string `jsonapi:"-"`
	Size        int
	Created     time.Time `jsonapi:"name=create-date"`
	Updated     time.Time `jsonapi:"name=updated-date"`
}
```

After making that change and running the tests, four tests fail with "invalid key "create-date" in json. Cannot be assigned to target struct xxxxx" where xxxxx is SimplePost for 3 tests and TaggedPost for 1.

Its behavior is very similar to what was fixed in https://github.com/manyminds/api2go/issues/197.

**Comment by sharpner** [comment]
thank you very much. We really shot ourselves in the foot with this one.

**Comment by wwwdata** [comment]
ok, wait a second, this sentence confuses me:

> I have a struct that contains both a field whose tag name is dasherized as well as an embedded struct.

does that mean that you have an api2go compatible struct as a field with a dasherized name? And you expected it to be marshalled as a normal struct, so something like

```json
{
    "data": {
        "attributes": {
            "body-style": {
                "field1": "content",
                "field2": "content"
            },
            "another field": "content"
        }
    }
}
```

**Comment by wwwdata** [comment]
But I can reproduce the `create-date` issue, so something is going wrong again.

**Comment by wwwdata** [comment]
yes, easy fix.. holy shit, I messed up the searching of embedded structs. If the unmarshaler found one, it only searches through the embedded struct and then returns, which was a mistake because more ifelds can be in the struct..

**Comment by wwwdata** [comment]
@obieq please test my PR if that works now as intended for you. So we can finally be sure that this issue is resolved :smile: thanks!

**Comment by obieq** [comment]
just grabbed latest and confirmed that my unit tests are passing now :+1:
