### ISSUE TITLE
Unmarshal array attributes not supported?

### ISSUE THREAD

**Issue by dopin** [manyminds/api2go#203]
Hi,

I'm trying to unmarshal this json
```json
{
  "data": [
    {
      "id": "87233c69-cf45-401c-aa73-7e65b4eda96a",
      "type": "images",
      "attributes": {
        "app_id": "fac73220-881a-4a32-bc18-bdaa71666a26",
        "image_name": "nginx:latest",
        "cmd": null,
        "is_running": false,
        "instances": 6,
        "mem": 512,
        "envs": null,
        "port_mappings": null,
        "ports": [
          {
            "protocol": "tcp",
            "number": "80"
          }
        ]
      },
      "relationships": {
        "app": {
          "data": {
            "type": "apps",
            "id": "fac73220-881a-4a32-bc18-bdaa71666a26"
          }
        }
      }
    }
  ]
}
```

The `ports` attribute is an array data.
So I wrote a code like this

```go
type Image struct {
	Envs         []map[string]interface{} `jsonapi:"name=envs"`
	Ports        []map[string]interface{} `jsonapi:"name=ports"`
	PortMappings []map[string]interface{} `jsonapi:"name=port_mappings"`
	ID        string
	ImageName string    `jsonapi:"name=image_name"`
	CreatedAt time.Time `jsonapi:"name=created_at"`
	UpdatedAt time.Time `jsonapi:"name=updated_at"`
	App       *App      `jsonapi:"-"`
	Mem       int       `jsonapi:"name=mem"`
	AppId     string    `jsonapi:"name=app_id"`
	Instances int       `jsonapi:"name=instances"`
	isRunning bool      `jsonapi:"name=is_running"`
	Cmd       string    `jsonapi:"name=cmd"`
}

func (i Image) GetID() string {
	return string(i.ID)
}

func (i *Image) SetID(ID string) error {
	i.ID = ID
	return nil
}

func (i *Image) SetToOneReferenceID(name, ID string) error {
	if name == "app" {
		if ID == "" {
			i.App = nil
		} else {
			i.App = &App{ID: ID}
		}

		return nil
	}

	return errors.New("There is no to-one relationship with the name " + name)
}
```

But it panics.

```
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method

goroutine 1 [running]:
reflect.valueInterface(0x2e21c0, 0xc8203e80c0, 0xe1, 0x1, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/reflect/value.go:912 +0xe7
reflect.Value.Interface(0x2e21c0, 0xc8203e80c0, 0xe1, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/reflect/value.go:901 +0x48
github.com/manyminds/api2go/jsonapi.UnmarshalInto(0xc8204842d0, 0x11a4080, 0x3cc280, 0xc82052ce38, 0x0, 0x0)
	project/vendor/src/github.com/manyminds/api2go/jsonapi/unmarshal.go:272 +0x1faf
github.com/manyminds/api2go/jsonapi.Unmarshal(0xc8204842d0, 0x2c5800, 0xc820129ae0, 0x0, 0x0)
```

I'm sorry if I'm doing something wrong or missing reading the docs again but could you tell me how to fix this?

**Comment by sharpner** [comment]
On a first quick look, have you tried exporting `isRunning`? Currently its privated and should be `IsRunning`.

But we will look into it. thx!

**Comment by dopin** [comment]
Oh my g.. :scream:  It works. Thank you again. :bow:

**Comment by sharpner** [comment]
Sure thing, I will improve the error message since it shouldn't panic so hard. :-)

**Comment by dopin** [comment]
By the way, Is it possible to unmarshal array attribute to a `[]struct` ?

```go
type Image struct {
	//...
	Ports        []*ImagePort             `jsonapi:"name=ports"`
	//...
}

type ImagePort struct {
	Protocol string `jsonapi:"name=protocol"`
	Number   string `jsonapi:"name=number"`
}
```

**Comment by wwwdata** [comment]
hm yes, we should just output an error without a panic

**Comment by wwwdata** [comment]
@dopin yes that array attribute should work too. Try it out

**Comment by dopin** [comment]
I got an error message: `Could not set field 'Ports'. Value '[map[protocol:tcp number:80]]' had wrong type`.

**Comment by wwwdata** [comment]
it also does not work if you use without pointer `[]ImagePort` type?

**Comment by dopin** [comment]
No, it doesn't work. :sweat:

**Comment by sharpner** [comment]
Could you open another issue for this?

**Comment by wwwdata** [comment]
ok, that is something we didn't test.

But if you use jsonapi and have a 1-n reference which this `Ports` is, you should make it a real reference. Or why do you embed this? jsonapi is all about normalization.

**Comment by sharpner** [comment]
and on a side note, you only need to specify the jsonapi="name" attribute if it differs from the fields name :-)

**Comment by dopin** [comment]
@sharpner Yes, I will open an issue for that.
I removed the tags from Image struct but it didn't work. I think I should double check the document.

@wwwdata I have some data that is just json. I think I can make `ports` to a relationship but there're some other data -like cache-  fetched from another api. So I wanted to know the way to unmarshal an array attribute.

**Comment by wwwdata** [comment]
ok, we will add support for that and link that to your new issue.

**Comment by dopin** [comment]
Thank you. I've created the issue #204.
