### ISSUE TITLE
Unmarshaling array attributes into array structs

### ISSUE THREAD

**Issue by dopin** [manyminds/api2go#204]
Hi,

This is another question about unmarshaling an array attribute related to #203 .
Unmarshaling array attributes into `[]map[string]interface{}` works. (Thanks for helping me!)
But it doesn't seem to work when it's into struct.

```go
type Image struct {
	Ports []ImagePort          `jsonapi:"name=ports"`
}

type ImagePort struct {
	Protocol string `jsonapi:"name=protocol"`
	Number   int    `jsonapi:"name=number"`
}
```

It doesn't work when it's a pointer `Ports[]*ImagePort`.

How can I unmarshal array attributes to structs?

**Comment by wwwdata** [comment]
Ok, this is not a question, this is a new feature request :smile:

**Comment by dopin** [comment]
Oh, I think it would be nice if it's supported.
wish I could create a PR to this... I need to learn Go more.

**Comment by wwwdata** [comment]
hm, this should also work after merging #202

**Comment by dopin** [comment]
Thank you! I will try it soon.
