### ISSUE TITLE
Fallback to `json` field tags for Marshal/Unmarshal?

### ISSUE THREAD

**Issue by interlock** [manyminds/api2go#206]
Our models are a little more universal than just jsonapi and already have tags for the json encoder:

```go
type User struct {
 Id int64 `json:"id"`
 Name string `json:"name"`
}
```

`Jsonify` https://github.com/manyminds/api2go/blob/master/jsonapi/helpers.go#L62 doesn't match our specs.

Adding duplicate data `jsonapi:name="id";json:"id"` can be a source of simple, but frustrating mistakes. e.g. typo in one but not the other.

I propose we fallback to using a `json` tag if it exists to get the name in func `GetTagValueByName` https://github.com/manyminds/api2go/blob/master/jsonapi/helpers.go#L86

This could open the door up to get omitempty and other tags that appear to be mirrored in jsonapi from json.

**Comment by wwwdata** [comment]
hm I guess a fallback cannot hurt. If you have both tags, the normal go marshaler/unmarshaler can behave differently than the one from api2go. But if the api2go marshaler/unmarshaler does not find the `jsonapi` tag and there is a `json` tag, it should use that. 

@interlock do you want to implement it?

**Comment by interlock** [comment]
I'll have a PR in tonight.

**Comment by sharpner** [comment]
I don't like a fallback very much. 

It would A) break existing applications that rely on api2go using default behaviour when there are json tags and B) make it complicated to use api2go with already existing structs that also already got json tags.

How about making the tagName injectable/configurable? 
This way api2go would at least behave predictable and not use any fancy logic internally. 

The [validator](https://github.com/go-playground/validator) package is doing it this way, I guess there were similiar discussions. 

I'm sorry that you already started working on it, but it was 2am here :P

**Comment by wwwdata** [comment]
hm yes @sharpner is right, we should make this configurable too.

**Comment by interlock** [comment]
So any suggestions would that would look like?

The marshaller is decoupled from api2go, communicating configuration could only happen on the tags or perhaps as an implemented interfaces on the interface{} being passed around.

If the idea is to use another tag to configure it, that defeats my motivation to do it. We may as well add the jsonapi tag to mirror our json tags.

**Comment by sharpner** [comment]
No another tag would not be the solution. I am thinking like introduction something like `UnmarshalWithOptions`

Where options can contain a custom tag for reflection settings....

**Comment by interlock** [comment]
That could work @sharpner . Thoughts on exposing ./jsonapi as a set of interfaces with a default implementation living there? If we made that tag lookup an interface one could simply embed that default implementation and override that one func (or any other for that matter) to get the behaviour they need.

Moving stuff like that to interfaces and implementation over config is often the `golang` way, no?

**Comment by sharpner** [comment]
So I've given it a lot of thought -.-

At first I thought "yay interfaces" for this but I don't think it would grow nicely.

If we would start now with an interface for our new setting:
```go
type TagNamer() interface {
   TagName() string
}
```
in the future we will get more option interface provider
```go
Type FancySettingGiver() interface {
  FancySetting() bool
}
```
this would leave use the only options to have a weak type hint on interface{} for our options struct.
```go
UnmarshalWithOptions(....,  options interface{})
```

So I guess there are only two options left imho, either use an options struct (like for example [tls.Config](https://golang.org/pkg/crypto/tls/#Config))
```go
type MarshallingOptions struct {
 TagName string
}

UnmarshalWithOptions(....,  options MarshallingOptions{})

options := MarshallingOptions{TagName: "foo"}
```
which would also be BC compatible if we specifically ask the user to only use named structs...

or the use of generic settings interfaces:
```go
type SettingProvider interface {
   GetSetting() (string, string)
}
```

and a function like 
```go
UnmarshalWithOptions(....,  options []SettingsProvider)
```

I hope I did not misunderstood you, and wrote to much :D 

What do you think? Did I miss anything?

**Comment by wwwdata** [comment]
hm, I guess that we will need some more configuration options in the future. So we have to do this right. 

For me, the simplest approach is to use a config struct like in the `tls.Config` example. Yes, if users use structs correctly, which means they use "named" struct, this will not break if they update api2go. But even if they update api2go and don't use named structs, it is not such a big thing. The go compiler will tell them `too few values in struct initializer` and it will take a couple of minutes to either switch to named struct usage or to add the missing configuration options.

Are there any other best practices from popular libraries or packages that we could check out?

**Comment by sharpner** [comment]
the stdlib mostly uses Options structs. `jpg.Options` `gif.Options` etc so I think we should go with that.

@interlock would that solution work for you? You could then UnmarshalWithOptions(..., Options{StructName: "json"}) and it would behave like a "fallback" to json.

**Comment by interlock** [comment]
In the context of encoders, interfaces are the convention in stdlib right now. Providing an interface, MarshalAPIJSON/UnmarshalAPIJSON would solve this issue for us at the moment.

The issue I can see with an `Options` struct in the future is that we continue to use configuration options to programatically add features when we could leave it to an interface and the implementer to add that specific functionality they require. This keeps code like my PR #207 out of api2go and makes it my responsibility to maintain. 

The trend of good lib's in golang has been to expose interfaces where it is possible the consumer of the library may want a different behaviour than was is commonly implemented. I think this is one of those cases.

**Comment by sharpner** [comment]
I don't see how it would be the responsibility of the user to implement this feature. 

We would allow a you to specify the name of the tag which should be used for marshalling/unmarshalling. 

We would never allow option switches/settings were an interface would be better. 
I just do not see a way how we could use an interface here that wouldn't make it overly complicated or hard to extend in the future.  

But please, If you got an idea that we missed, let us know.

**Comment by interlock** [comment]
The problem is that the api2go tag syntax `jsonapi:"name=uber_field" to specify a name is different than encoding/json format `json:uber_field`. That means we will need to insert and maintain logic to look at which tag you are specifying would have to be aware that `json` is different and use a different mechanism to pull the name. 

That also makes testing and maintenance a considerably larger overhead of this project. I actually think my PR #207 does more harm than good at this point. The idea that someone would want to control Marshal/Unmarshal for more than just the name to encode the field as is far more likely. What if someone needs `Time` encoded differently when it's name ends in `_ts` or concat an array of strings on encoding?

Using the json encoding interfaces, that would be as simple as making an alias type that implements the interface MarshalJSON and UnmarshalJSON. There is no equivalent with api2go. That is the problem we should be addressing.

**Comment by wwwdata** [comment]
hm, you are right @interlock 
what currently sucks about api2go is the lack of standard compatible Marshaling and Unmarshaling. Like you said if a struct has a field that implements it's own `MarshalJSON` from the `Marshaler` interface, this should be used to marshal it. The only thing that api2go needs to do, is provide the structure around the payload, for example putting stuff into the `attributes` object in the json and so on. Currently we just copy fields around into a new `map[string]interface` which destroys their potential implementations of these interfaces, right?

I have some ideas and will work on improving this in #202.

**Comment by sharpner** [comment]
Okay now I get what you mean. Of course that is another issue that you can't directly influence marshalling/unmarshalling behaviour. 

But even if we would provide (and what we'd really like to have!) interface methods, the field name decision comes earlier I believe. That's why, even json uses those tags instead of letting you change field names.

**Comment by sharpner** [comment]
haha timing

**Comment by interlock** [comment]
@sharpner @wwwdata I could override the field naming in a Marshaller on the model for naming. Is it the ideal solution, nope. Does it work and we can ship our api if we do that, yup! :grinning:

**Comment by wwwdata** [comment]
hmm, what to do now? Can you wait with this PR until we worked out our refactoring? I guess if we do the completely standards compatible way, it will be obsolete anyway, because all the original json tags will be used anyways. So our custom `jsonapi` tags, if we keep them at all, will be used as a fallback if no original json tags were found.

But I guess this makes more sense. Api2go should marshal everything from a struct like the normal go marshaler does and decorate that with all the jsonapi stuff, like `type`, `id`, the relationships and so on. The payload will land into `attributes` and will be exactly the same, as if you marshal the struct with the standard `json.Marshal` method from go. Does this sound good @interlock ?

**Comment by interlock** [comment]
Sounds good @wwwdata . How can I help?

**Comment by wwwdata** [comment]
i'll start soon, would be awesome to have another good reviewer/tester when I start this :)

**Comment by interlock** [comment]
@wwwdata We may fork and add some hacks/patches to work around in the meantime. We have an internal release coming this Wednesday, first production deploy of api2go for us.

**Comment by sharpner** [comment]
wow that's awesome to hear! good luck for the go live!

**Comment by wwwdata** [comment]
we will soon merge the refactoring in, after that your custom `jsonapi` tags are gone and we stick to the standard `json` tags. If you like @interlock we would really appreciate your feedback about the refactoring.

**Comment by xomaczar** [comment]
It's great to hear about the upcoming release of api2go.v1. Getting rid of jsonapi tags is great, however it creates a conflict for system where json serialization should differ from jsonapi format. Ignoring a given field I.e. SomeStructID from jsonapi will now require json:"-", which inadvertently will ignore this field when json.Marshal is called.

**Comment by interlock** [comment]
@xomaczar In that case you can create a custom marshaller/unmarshaller to resolve that.

**Comment by xomaczar** [comment]
Can you elaborate? Are you suggesting implementing a custom marshaller/unmarshaller for jsonapi resource - I was hoping api2go would do that

**Comment by xomaczar** [comment]
I am embedding structs that have nothing to do with jsonapi, jsonapi is used solely for server/client interaction.

**Comment by interlock** [comment]
I think a concrete use case description would help. You can override how encoding/json will choose fields by implementing  Marshall and Unmarshall. Not at a computer right now otherwise I would link to the golang docs for it. 



—

**Comment by wwwdata** [comment]
@xomaczar interesting topic. Could you explain your use case so we can think about it? We want to make it right for the the version 1.0 of api2go.

**Comment by wwwdata** [comment]
closing this, we are using the standard `json` tags now.

**Comment by xomaczar** [comment]
@wwwdata I apologize for the late response. Here's the use case I had in mind...
Imagine I have an external package (mine) with some models:
```go
//projectA/models/order.go
package models

type Order struct {
   Name string
   OrderItemIDs  []uuid  `jsonapi:"-"`
}

type OrderItem struct {
   ProductID uuid `jsonapi:"-"`
   OrderID uuid  `jsonapi:"-"`
}
```
The default JSON marshalling/unmarshalling is used by projectA for communication purposes. Let's say there is a client proxy that it provides for talking to an external services which use JSON serialization/deserialization for sending payload/etc.
```go
//projectA/client.go
func SubmitOrderFromForm(form Order) Order {
  orderJSON, _ := json.Marshal(form)
  out = rpc.Call("SubmitOrder", orderJSON)
  var createdOrder Order
  json.Unmarshal(out, &createdOrder)
  return createdOrder
}
```
Now there is a web-api project that acts as an adapter between the client web app and the packageA. The web-api provides JSONAPI for client communication using api2go.
```go
//web-api/resources/order.go
import "projectA/models"
type OrderResource struct {
   models.Order
}
//Implements api2go interfaces to support JSONAPI relations, links, etc.
```
Embedding a projectA/models is a must have as it allows compiler to catch issues before hand. I don't want to manually create each property and use some sort of mapping to copy values from packageA.models to web-api.models and vice version JSONAPI tags were/are very convenient to include/exclude fields from JSONAPI document while at the same time not interfere with default json encoding.

**Comment by wwwdata** [comment]
ok that makes sense, basically you have two different marshaling/unmarshaling use cases that need to produce different results. One is the internal json format and the other is the external jsonapi compatible json format. 

Currently our main struct for handling the data payload looks like this:

```go
type Data struct {
	Type          string                  `json:"type"`
	ID            string                  `json:"id"`
	Attributes    json.RawMessage         `json:"attributes"`
	Relationships map[string]Relationship `json:"relationships,omitempty"`
	Links         *Links                  `json:"links,omitempty"`
}
```

We just take the struct and marshal it into the `Attributes` field. Then we fill out the rest of the fields and Marshal the complete `Document` with `json.Marshal` again to the jsonapi compatible json document.

In order to support a different tag for our jsonapi marshaling we will have to implement a different marshaler/unmarshaler for `Attributes`, the whole document can be marshaled with the standard json marshaler/unmarshaler from go.

Here is the main part of this process: https://github.com/manyminds/api2go/blob/master/jsonapi/marshal.go#L171

I don't know what the best solutino for this is yet. What you could do is of course implement your own https://golang.org/pkg/encoding/json/#Marshaler interface for the struct that uses different tags for jsonapi marshaling. 

Do you have any good implementation ideas that do not heavily rely on the reflection package? :D Because we were down this path before and the old implementation iterated over all the fields and read the jsonapi tags and then build a new `map[string]interface{}` of that new beast that could then be marshaled.

If you think about a solution: ignore api2go for it. Just think like this: You are using `json.Marshal` in 2 different use cases and need different output.

**Comment by xomaczar** [comment]
@wwwdata reflect is what comes to mind - then how's it different from v0. I just wanted to showcase the usefulness of jsonapi tags
