### ISSUE TITLE
json.RawMessage

### ISSUE THREAD

**Issue by wwwdata** [manyminds/api2go#208]
https://godoc.org/encoding/json#RawMessage

It was pointed out by @trapias in our gitter chat, that `json.RawMessage` types are not working.

**Comment by sharpner** [comment]
What would be the expected result? I am not familiar with json.RawMessage :/

**Comment by wwwdata** [comment]
I just opened this ticket to collect information for now. `json.RawMessage` is a very dirty thing and as far as I understand the official godoc example, it can be used to retrieve content out of a json and manually Unmarshal it in another struct. The type of that struct is not exactly determined. That's why they used the field `Space` as a type-switch. I copied the example:

```go
type Color struct {
    Space string
    Point json.RawMessage // delay parsing until we know the color space
}
type RGB struct {
    R   uint8
    G   uint8
    B   uint8
}
type YCbCr struct {
    Y   uint8
    Cb  int8
    Cr  int8
}

var j = []byte(`[
		{"Space": "YCbCr", "Point": {"Y": 255, "Cb": 0, "Cr": -10}},
		{"Space": "RGB",   "Point": {"R": 98, "G": 218, "B": 255}}
	]`)
var colors []Color
err := json.Unmarshal(j, &colors)
if err != nil {
    log.Fatalln("error:", err)
}

for _, c := range colors {
    var dst interface{}
    switch c.Space {
    case "RGB":
        dst = new(RGB)
    case "YCbCr":
        dst = new(YCbCr)
    }
    err := json.Unmarshal(c.Point, dst)
    if err != nil {
        log.Fatalln("error:", err)
    }
    fmt.Println(c.Space, dst)
}
```

So from that I guess, that the field of the `json.RawMessage` should just stay a valid json document. Which means a `[]byte` with json in it, so it can then be Unmarshaled manually after api2go unmarshaled the document.

But I am very sure that there are better more elegant ways to solve this problem than this approach.

**Comment by sharpner** [comment]
ok then let's wait for a valid use- case before implementing this edge case .-)

**Comment by wwwdata** [comment]
Will close this after #202 it just works then.
