### ISSUE TITLE
Accept other status codes as response for update

### ISSUE THREAD

**Issue by mantenie** [manyminds/api2go#212]
Sometimes I want to check if the user is authorized to change some resource data.
If the user is not authorized, I want to return http status 401 but api2go returns 500 and the error message: ```invalid status code 401 from resource users for method Update```

**Comment by sharpner** [comment]
Yeah you're right, atm we are to restrictive. http://jsonapi.org/format/#crud-updating `A server MAY respond with other HTTP status codes.` We should open up the API and allow all status codes.

**Comment by wwwdata** [comment]
stop, we are restricting the 2xx status codes, not the error codes. You can use all the 4xx and 5xx status codes, if you correctly fill out our error struct. So please just return an error struct with the correct code, see: https://github.com/manyminds/api2go/blob/master/error.go#L13

**Comment by mantenie** [comment]
Okay, thanks! That helps.
