### ISSUE TITLE
Unmarshaling from JSON with null values?

### ISSUE THREAD

**Issue by dennisfaust** [manyminds/api2go#214]
encoding/json's Marshal ignores null attribute values. Your jsonapi/MarshalToJSON functions accept the nulls if the target is defined as zero.string etc. and overwrites the existing values. That is the behavior I would like in my API. Is the most sensible way to get this behavior to create a custom ContentMarshaler using jsonapi.MarshalToJSON and jsonapi.UnmarshalFromJSON?

**Comment by wwwdata** [comment]
You mean if you are usings golangs normal `json.Marshal` and `json.Unmarshal` you want to have a different behavior for these null types? Go encodes and decodes json based on the implemented `Marshaler`and `Unmarshaler` interfaces. So if you want to change the behavior of it, you will have to implement them. See: https://godoc.org/encoding/json#Marshaler

But I am not so sure that I understood your question. Can you maybe give an example?

**Comment by dennisfaust** [comment]
In this test: https://github.com/manyminds/api2go/pull/213/files#diff-59126cff0cd8c2e7fe0eff5325b48142R660
I demonstrate the desired behavior. I'd like to pass in nulls in the JSON payload and have that set the null/zero.* fields to their golang zero value regardless of what their current value is.

**Comment by sharpner** [comment]
Well, that is not actually an api2go issue, isn't it? 

If you like to change the default unmarshal/marshal behaviour have a look at its interfaces https://golang.org/src/encoding/json/decode.go#L93 .

**Comment by wwwdata** [comment]
you did check http://gopkg.in/guregu/null.v2/zero ?

**Comment by dennisfaust** [comment]
Further investigation showed that it is indeed an api2go issue. My test was flawed and would always pass because UnmarshalFromJSON creates a new object and it's understandably full of zero values. That test needs to be reworked or most likely removed. But investigating this with a colleague pointed out the real problem which I've demonstrated in a new PR: https://github.com/manyminds/api2go/pull/215

**Comment by wwwdata** [comment]
can we close this issue? I also checked the behavior in my refactoring task. If you correctly marshal/unmarshal into the zero types in a struct, it leaves the values in it and overrides the `IsValid` status with false. So everything will be better after we get rid of our huge reflection madness.
