### ISSUE TITLE
`handleUpdate` should not pass an empty information{} to Marshaller

### ISSUE THREAD

**Issue by interlock** [manyminds/api2go#216]
If the resource in question implements the relationship related interfaces this causes a it to attempt to run functions on the empty `information{}` resulting in a `panic()`.

Fix is to pass along the info as the other handlers do and pass that to the marshaller.

https://github.com/manyminds/api2go/blob/master/api.go#L728

**Comment by interlock** [comment]
Fix looks like this: https://github.com/picatic/api2go/commit/6fcce645794dac6e5a2ef4aea794e207fc1eb5eb

Can submit a cherry picked patch, but it looks like a huge refactor is coming... so YMMV.

**Comment by wwwdata** [comment]
ok, this is an api thing, so a bugfix with a small testcase would be awesome. The refactoring mainly affects marshal/unmarshal stuff but I will have to adept to the new behavior in the api as well, but that should not change the whole thing, only minor stuff.
