### ISSUE TITLE
Is there a way to include charset=utf-8 at the end of a Response header

### ISSUE THREAD

**Issue by abrykajlo** [manyminds/api2go#217]
We are using utf-8 in our database and require that our reponse headers contain content-type as such:

```
"Content-Type": "application/vnd.api+json; charset=utf-8"
```

#119 looked like it may have fixed this. By adding your own marshalers you can include

```
var marshalers = map[string]ContentMarshaler {
    "application/vnd.api+json; charset=utf-8": JSONContentMarshaler{},
}
```

This should in theory be used after `httputils.NegotiateContentType` gets executed here: https://github.com/manyminds/api2go/blob/7e85e66ad917fb1269891367fa712207fd06f33e/api.go#L1130

In fact what happens inside that function here: https://github.com/golang/gddo/blob/master/httputil/negotiate.go#L47

 [ParseAccept](https://github.com/golang/gddo/blob/master/httputil/header/header.go#L171) will filter out any header which contains any extensions which seemed to be the reason for #119 any extensions will be filtered and will always use the defaultContentTypHeader which is "application/vnd.api+json"

**Comment by wwwdata** [comment]
hm, sorry for the late response. I will continue my huge refactoring stuff tomorrow and after that I can look into this issue as well or maybe @sharpner can take a look.

Or do you have an idea how to fix it? Would be awesome if you could write a small test for the wrong behavior and your fix for it.

**Comment by interlock** [comment]
The middleware handling I added with #152 makes this kinda painful to override as well. I don't suppose in this refactor we could slide the middleware handling closer to a chained handler? I know @kevpie had some thoughts on that. AKA, he didn't like my easy mode middlewares ;-)

**Comment by wwwdata** [comment]
our big PR is merged and it's now possible to set the `ContentType` in the `API` struct.
