### ISSUE TITLE
Allow different types in one many-relationship

### ISSUE THREAD

**Issue by mantenie** [manyminds/api2go#218]
In my case I have an ordered list of resources of different types.
I want to return them in a single reference array.

In my GetReferencedIDs I dynamically set the different types:
```
// GetReferencedIDs MarshalLinkedRelations
func (p Path) GetReferencedIDs() []jsonapi.ReferenceID {
	result := []jsonapi.ReferenceID{}

	for _, elem := range p.PathElements {
		var returnType string

		switch elem.Type {
		case "Question":
			returnType = "questions"
		case "Idea":
			returnType = "ideas"
		case "Problem":
			returnType = "problems"
		}

		result = append(result, jsonapi.ReferenceID{
			ID:   elem.ID,
			Type: returnType,
			Name: "path-elements",
		})
	}

	return result
}
```

But the api returns in my ```path-elements``` field for every resource the same type and ignores the various types.

Example output:
```
"relationships": {
            "path-elements": {
                "data": [
                    {
                        "id": "f48aead1-5721-4bf0-8801-301006013b51",
                        "type": "questions"
                    },
                    {
                        "id": "20d3683e-9982-410d-a77a-7728d4f625f9",
                        "type": "questions"
                    },
                    {
                        "id": "e1d923cd-0882-4978-8f1d-1f5409094e71",
                        "type": "questions"
                    },
                    {
                        "id": "713536d3-7ce6-4035-99ec-c73310e60dc6",
                        "type": "questions"
                    },
                    {
                        "id": "068c57b6-a0d2-4354-b6e6-71af7f12bfce",
                        "type": "questions"
                    }
                ],
                "links": {
                    "related": "/v1/paths/f48aead1-5721-4bf0-8801-301006013b51/path-elements",
                    "self": "/v1/paths/f48aead1-5721-4bf0-8801-301006013b51/relationships/path-elements"
                }
            }
        },
```

**Comment by wwwdata** [comment]
ok, in theory this should be a valid and doable case. I guess the problem is this line here: https://github.com/manyminds/api2go/blob/master/jsonapi/marshal.go#L248

can you check this and open a pull request? This must be changed so that it always takes the type out of the current `ReferenceID` item.

**Comment by wwwdata** [comment]
@sharpner what do you think about this? Normally one relationship should be of the same type, that's why we have the `Type` Field in our `Reference` struct. But we can easily allow this by just taking the type that is returned for the toMany Relationship.

**Comment by wwwdata** [comment]
For the refactoring I am currently doing I am thinking about this too. I guess we don't need a type at all and it would be more useful to only specify the Name and whether it's a toOne or toMany relation, no more is needed.

**Comment by wwwdata** [comment]
I opened a PR with the fix for you @mantenie 
You should test it if this was what you meant and if it works for you now.

**Comment by mantenie** [comment]
Looks good. Thanks for implementation.
