### ISSUE TITLE
how to respond with json {"data": null} when GET single non-existing resource?

### ISSUE THREAD

**Issue by arcijsg** [manyminds/api2go#222]
Firstly, thanks for the great work - the code is a pleasure to read and a great source for learning to me!

jsonapi specification says:

    A server MUST respond to a successful request to fetch an individual resource with a resource object or null provided as the response document's primary data.
    null is only an appropriate response when the requested URL is one that might correspond to a single resource, but doesn't currently.

Example:

    HTTP/1.1 200 OK
    Content-Type: application/vnd.api+json
    {
        "links": {
            "self": "http://example.com/bills/108"
        },
        "data": null
    }

How do i construct such a response in my FindOne() CRUD handler?
I have tried to return both:

    return &Response{Res: nil, Code: http.StatusOK}, nil

and

    return &Response{Code: http.StatusOK}, nil

from the handler and get a "nil cannot be marshalled" error.

My Response type is a trivial:

    type Response struct {
  	  Res  interface{}
	  Code int
    }

    func (r Response) Result() interface{} {
        return r.Res
    }

What am i missing or doing wrong?

**Comment by wwwdata** [comment]
Hi, good catch, yes, I guess we completely forgot this use case. We will look into it.

**Comment by sharpner** [comment]
thank you for using api2go. 

You are doing nothing wrong, this is one use-case we currently missed. Thanks for reporting it.

**Comment by wwwdata** [comment]
ok, the fix is easy, I looked into the code, we just have to remove the `nil` check in `jsonapi/marshal.go` but we should do this after we merge in the huge refactoring #202 

if you want @arcijsg you can try out this branch too and check if  your app still works. You will have to change the annotations from `jsonapi` to `json` and manually name all your fields, but then it should work like before.

**Comment by wwwdata** [comment]
ok I will start working on this, basically we have 2 use cases that must work:

empty collection:

```json
HTTP/1.1 200 OK
Content-Type: application/vnd.api+json

{
  "links": {
    "self": "http://example.com/articles"
  },
  "data": []
}
```

empty single resource:
```json
HTTP/1.1 200 OK
Content-Type: application/vnd.api+json

{
  "links": {
    "self": "http://example.com/articles/1/author"
  },
  "data": null
}
```

**Comment by arcijsg** [comment]
Thanks a lot - it's nice to have a reply and a fix so soon! :)
Switched to using 10.-RC1 branch and it's working very well!

**Comment by sharpner** [comment]
thanks for the feedback! Much appreciated :-)
