### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by Moddus** [manyminds/api2go#229]
Hi there,
i want to add basic auth to my api. Actual i'm using your ```func (api *API) UseMiddleware(middleware ...HandlerFunc)``` function. For my test case i'm using the following implementation:

```
func basicAuth(c api2go.APIContexter, w http.ResponseWriter, r *http.Request) {
	http.Error(w, "authorization failed", http.StatusUnauthorized)
}
```

This implementaion should reject all api call and respone with "authorization failed". But in this case the routing process of api2go is still on.
My question: Is there a way to define a middleware and prevent api2go to route further? After my middleware the rounting chain should stop.

Thanks,
Moddus

**Comment by sharpner** [comment]
You can wrap your handlers before registering them, 
did you have a look at #22 already?

If you need this done in a middleware, I currently no out of the box feature for it.

**Comment by Moddus** [comment]
Yes, i've looked at #22. What about thinks like ```AddResource``` how I'm possible to wrap this kind of things ?

**Comment by sharpner** [comment]
Let me try to explain by using some code:
```
api := api2go.NewAPI("v1")
api.AddResource(Post{}, &PostsSource{})
http.ListenAndServe(":8080", wrapHandler(api.Handler()))
```

where 
```
func wrapHandler(handler http.Handler) ...
```
could implement basic auth. 

This would count on all requests though. Do you need it only for specific context?

**Comment by Moddus** [comment]
Now i got it ! Thanks **sharpner** for your help. I really appreciate it.

**Comment by sharpner** [comment]
Glad I could help ;-)
