### ISSUE TITLE
Updating Resource relationship throws 406 attributes is mandatory

### ISSUE THREAD

**Issue by tanmayambre** [manyminds/api2go#234]
Hello 
I refer to you to the following specification. 
http://jsonapi.org/format/#crud-updating-resource-relationships.

I am trying to update relationship via curl using the spec mentioned. Note that there are no "attributes"  to be updated in the third curl request only a "relationships".

I used the provided crud_example.go to test this. 
```
#create a user
curl -X POST http://localhost:31415/v0/users -d '{"data" : {"type" : "users" , "attributes": {"user-name" : "marvin"}}}'

#create a chocolate
curl -X POST http://localhost:31415/v0/chocolates -d '{"data" : {"type" : "chocolates" , "attributes": {"name" : "Ritter Sport", "taste": "Very Good"}}}'

#update sweet relationship of an user
curl -X PATCH http://localhost:31415/v0/users/1 -d '{"data":{"type":"users","id":"1","relationships":{"sweets":{"data":{"type":"chocolates","id":"1"}}}}}'

```
The last request should have returned a 204 No Content. Instead I get the following 406 error.
```
{"errors":[{"status":"406","title":"missing mandatory attributes object"}]}
```

Please advice if I should be expecting the message or is a bug. It seems that this has changed recently.

**Comment by wwwdata** [comment]
you are right, the update method now always expects an `attributes` object. We forgot the use case where we only want to replace all the `relationships` of a resource. 

if `attributes` is added, it works 
```
curl -X PATCH http://localhost:31415/v0/users/1 -d '{"data":{"type":"users","id":"1","attributes": {},"relationships":{"sweets":{"data":[{"type":"chocolates","id":"1"}]}}}}'
```

apart from that, you can also use the dedicated routes to manipulate relationships which should be working correctly (because we have tests for them). 

So, for example this is working as well:
```
curl -X DELETE http://localhost:31415/v0/users/1/relationships/sweets -d '{"data":[{"type":"chocolates","id":"1"}]}'
```

Or add one again:
```
curl -X POST http://localhost:31415/v0/users/1/relationships/sweets -d '{"data":[{"type":"chocolates","id":"1"}]}'
```

but good catch! This is a bug because the specification says it should be working.

**Comment by wwwdata** [comment]
we implemented it wrong, it's totally fine to leave out an `attributes` object:

> A resource object MUST contain at least the following top-level members:
> - id
> - type
> Exception: The id member is not required when the resource object originates at the client and represents a new resource to be created on the server.

> In addition, a resource object MAY contain any of these top-level members:

> - attributes: an attributes object representing some of the resource's data.
relationships: a relationships object describing relationships between the resource and other JSON API resources.
> - links: a links object containing links related to the resource.
> - meta: a meta object containing non-standard meta-information about a resource that can not be represented as an attribute or relationship.

the incorrect check is in the `jsonapi/unmarshal.go` file inside the `setDataIntoTarget` function.

**Comment by tanmayambre** [comment]
Thanks for the response. While you are solving it the api should probably return 406 when "type" is not included. Probably you are solving it already. 
Currently POST without type 
```
curl -X POST http://localhost:31415/v0/chocolates -d '{"data" : { "attributes": {"name" : "Ritter Sport", "taste": "Very Good"}}}'
```
returns 
```
{"errors":[{"status":"500","title":"Type  in JSON does not match target struct type chocolates"}]}
```

Similarly ID field will also require checked for request that are not POST .Currently this happens.
```
curl -X PATCH http://localhost:31415/v0/chocolates/1 -d '{"data" : { "type":"chocolates", "attributes": { "taste": "Muy bueno"}}}'
{"errors":[{"status":"500","title":"Chocolate with id  does not exist"}]}
```

**Comment by wwwdata** [comment]
thx! We will fix all of these issues

**Comment by wwwdata** [comment]
i will also work on this this weekend, or do you already have fixed it and can open a PR @tanmayambre ?

**Comment by tanmayambre** [comment]
Hi I don't have a solution currently. I will try solving it this week
