### ISSUE TITLE
Update documentation.

### ISSUE THREAD

**Issue by dennisfaust** [manyminds/api2go#236]
The documentation is out of date. Using the encoding/json marshal, unmarshal etc. has made a couple of sections incorrect:

- the struct settings jsonapi:"" are now deprecated in favor of json:""?
- The section on using pretty marshaling is now incorrect or superfluous?
- api2go.NewAPIWithMarshalers doesn't exist anymore.

**Comment by sharpner** [comment]
thanks for the hint!
