### ISSUE TITLE
Struct tag "omitempty" not working?

### ISSUE THREAD

**Issue by dennisfaust** [manyminds/api2go#238]
According to the encodings/json documentation (https://golang.org/pkg/encoding/json/#MarshalI) it should be possible to use a tag like 'json:"password,omitempty"' to keep the password field from being included in the response at all. However, that is not the current behavior. Is this expected?

**Comment by wwwdata** [comment]
if the field is empty, it should be omited. But if you want to always exclude it, I would recommend to use the `json:"-"` tag which always excludes the field. Can you give an example?

**Comment by dennisfaust** [comment]
I'm working with a password field. I want it to be accepted so I can encrypt it and then save the encrypted value in another field. There is no password field in the db. Preferably, I'd be able to use the tag above, do my encrypting in the BeforeSave(), clear the password value with null.String and then have it not appear in the JSON returned payload. But that's not happening. Instead, I'm getting ("password": null) whether I have omitempty or not.

**Comment by wwwdata** [comment]
ah, so you are using the database null types. Maybe that is the issue. This is a struct and I guess the default Marshaler of go doesn't know it's empty value. I guess it works with a pointer and this stackoverflow thread says so as well: http://stackoverflow.com/questions/24345621/marshal-sql-nullstring-with-omitempty

Of course implementing a custom Marshaler will also work, but just using a pointer and setting it to nil should do the trick.

**Comment by dennisfaust** [comment]
I tried a nil pointer as well and the value was still in the response. Turns out that our client depends on that so it's not an issue for now. I'll look into it further when we next need to suppress a response.

Thanks!

**Comment by sharpner** [comment]
Yeah a pointer and omitempty should do the trick. But since it is not an issue for you anymore I'll close it.
