### ISSUE TITLE
Location header returns 2 forward slash "//users/1" Is this correct behaviour?

### ISSUE THREAD

**Issue by tanmayambre** [manyminds/api2go#240]
In crud_example.go code I stared the NewApi("") with no prefix as below 
```	
    port := 31415
	// api := api2go.NewAPIWithResolver("v0", &resolver.RequestURL{Port: port})
	api := api2go.NewAPI("")
	userStorage := storage.NewUserStorage()
```

Made a POST request as follows
```
curl -X POST http://localhost:31415/users -d '{"data" : {"type" : "users" , "attributes": {"user-name" : "marvin"}}}' -v
...
< Location: //users/1
...
```
I was expecting the Location header to be `/users/1`. 
Currently it adds a extra forward slash. `//users/1`
Is this the correct behaviour?

**Comment by wwwdata** [comment]
looks like a bug, we need a test and fix for this.
