### ISSUE TITLE
newbiew question

### ISSUE THREAD

**Issue by joeblew99** [manyminds/api2go#254]
I am using goa (https://github.com/goadesign) at the moment. Its allot like api2go !

Goa design also supports the JSONAPI standard too.

So i am kind of comparing the two and seeing what each can offer and also what they can learn from each other.

But from what i can see api2go is using runtime reflection, where goa is using code gen.
Big significant difference. I just wanted to know from the team.

Here is a DSL example for GOA:
https://github.com/goadesign/goa-cellar/blob/master/design/api_definition.go

As you can see form all the other folders above it, everything is code generated.

what i am interested in is the code gen / or reflection for the GUI:

But what i am tryign to do is generate the front end so that it sully supports modularisation.
Polymer, Angular, and maybe (not sure) react have all changed over to the app shell concept.
https://www.polymer-project.org/1.0/blog/routing

I am wondering if there is anything like this in Ember ?

What i am looking at is using gopherJS to code gen the client side code based on the JSONAPI standard. But i also want to make sure i have full Modularity of the routing.

I know this is a hell of a issue on github with lots going on, but i am hoping that we have a common goal for the architecture. I have done lots of DSL and MDA stuff with other systems and golang. SO my leaning is towards dong things to make it quicker and easier to build real world apps.

**Comment by sharpner** [comment]
well if you can use code generation over reflection you have probably the faster and more robust alternative. 

But as far as I can see goa allows you to create an api manually that confirms the jsonapi standard, but api2go automatically creates all those routes for you so you do not have to know how the jsonapi standard is defined.

Maybe your question is better asked on stackoverflow where someone who knows about both frameworks can reply to you. 

Additionally you are asking about javascript frameworks which it also be a different question on stackoverflow ;-)

**Comment by sharpner** [comment]
One thing to add: goa seems to be a complete framework that specifies how you have to do things, whereas you can use api2go together with different muxers, routers, etc...
