### ISSUE TITLE
Package Audit & Version 1.0 milestone

### ISSUE THREAD

**Issue by 256dpi** [manyminds/api2go#262]
I would like to make an audit of the whole package before considering an 1.0 release. This package forms the basis of a couple of projects I'm working on. In that sense I'm very interested in achieving a nice and stable API surface for the future.

Could you elaborate on you plans of releasing a version 1.0?

What would be good structure to work on that for you? Should I create Issues and PRs for everything, should we track the changes in a Milestone?

**Comment by 256dpi** [comment]
I'm raising this because I have my next PR https://github.com/256dpi/api2go/commit/8fd91b2f8a01afd13422e77c2d7b56a06eb840a6 already in the pipeline. ;)

**Comment by wwwdata** [comment]
In my opinion we should merge #261 and decide what needs to be done for a version 1.0 and create tickets for all things and link them to a Milestone 1.0. If we are ok with the new API and everything that's accessible from the outside, we should release 1.0 and then also keep that public API stable until a version 2.0 where it's allowed to break things. From there on, we should only add stuff to not break anything.

What's your opionin @sharpner?

**Comment by sharpner** [comment]
okay we agreed on this approach. So master will be unstable for a while. :-) I really like your next PR, the names make much more sense.

**Comment by 256dpi** [comment]
Sorry for taking so long to get back to you.

While reading the api2go source code to identify further improvements, I realized that the current concept of using interfaces to outsource detailed implementation will always be a limitation for my project. In that sense I had to decide that I will concentrate on a custom jsonapi implementation that is tailored for my needs. You can find it here: https://godoc.org/github.com/gonfire/jsonapi.

I was really eager in improving this library, it's really a pity that it didn't work out.

@sharpner Feel free to merge the branch I prepared to rename some structs.
