### ISSUE TITLE
PATCH is shown as allowed when doing an OPTIONS request, but returns "405 Method Not Allowed" when a PATCH request is attempted

### ISSUE THREAD

**Issue by RPiAwesomeness** [manyminds/api2go#264]
I understand that this may not be an api2go issue, perhaps just an issue with my implementation, but I am working on a project utilizing `api2go` and RethinkDB. 

As the bug title says, when I make an `OPTIONS` request to the endpoint `PATCH` is listed in the `Allow` header. However, if I attempt to make a `PATCH` request to that endpoint, I get a **405 Method Not Allowed** error back:

![selection_012](https://cloud.githubusercontent.com/assets/11481499/18233901/cbf39da8-72c2-11e6-8020-f3eb98a44598.png)

I have an Update method implemented that is returning an api2go.Response object pointer, so PATCH support *should* exist, if I'm understanding the example and the rest of the `api2go` documentation.

I will try and re-create the issue in as minimal code as possible and post a link to a gist on this issue as soon as possible.

**Comment by RPiAwesomeness** [comment]
Here's my Update method currently:

```golang
// Update implements the updating of a resource, satisfying api2go.DataSource interface
func (s UserResource) Update(obj interface{}, r api2go.Request) (api2go.Responder, error) {
	return &Response{Code: http.StatusOK}, nil
}
```

**Comment by wwwdata** [comment]
what exactly are you sending as payload in your request? I don't understand the screenshot. What also confuses me is the Content-Type that says `text-plain`

Updating should work with api2go, I just ran the example project and it was working fine in there.

**Comment by RPiAwesomeness** [comment]
@wwwdata Sorry about the delay, I started school this week and haven't had time to work on my project.

As for what I'm sending as payload, I've tried sending the payload two different ways:

* In the URL, in this form `localhost:8000/v1/users?username=RPiAwesomeness`, via httpie
* Without anything, via curl: `curl -X PATCH http://localhost:8000/v1/users`
* In JSON, via the Python requests module `requests.patch("http://localhost:8000/v1/users", json={"username": "RPiAwesomeness"}`

I'm not sure why the Content-Type is set to `text-plain`, I would assume that's what the server is accepting it as, but I have no real idea.

As for the screenshot, I was attempting to show that `PATCH` is listed as accepted when an `OPTIONS` request is made to that endpoint, but then is not allowed when an actual `PATCH` request is made.

**Comment by RPiAwesomeness** [comment]
@wwwdata I'm sorry I wasted your time. I've realized what my mistake was. I was trying to make a `PATCH` request to the `/v1/users` endpoint, which obviously shouldn't allow a `PATCH` request, since it's returning all of the records related to that endpoint. `PATCH`-ing to `/v1/users/<ID>` works just fine.

One thing I **did** notice is that this happens if I `PATCH` without any data to `/v1/users/<ID>`, this shows up. Any idea what would cause that? It doesn't happen in the example.
```
2016/09/10 21:05:58 The result does not contain any more rows
exit status 1
```

**Comment by wwwdata** [comment]
I guess that could be an error from your method that updates the database? Because api2go does not output any error messages that mentions rows.

**Comment by RPiAwesomeness** [comment]
@wwwdata Really? That's weird, because the code I have for that doesn't actually do anything, it just returns an empty Response reference: `return &Response{Code: http.StatusOK}, nil`.

**Comment by wwwdata** [comment]
It cannot come from our code.. you can search for `row` in it yourself and won't find anything.

Before actually getting to your Patch/Update Method, a `FindOne` get's called. And that can also trigger the database error. See; https://github.com/manyminds/api2go/blob/master/api.go#L617

https://github.com/manyminds/api2go/blob/master/api.go#L615-L620

```go
func (res *resource) handleUpdate(c APIContexter, w http.ResponseWriter, r *http.Request, params map[string]string, info information) error {
	id := params["id"]
	obj, err := res.source.FindOne(id, buildRequest(c, r))
	if err != nil {
		return err
	}
```

**Comment by RPiAwesomeness** [comment]
Aha, that might be what's causing it. Strange that it is causing the whole program to crash. I will look into this, thanks for the help :)

**Comment by wwwdata** [comment]
so, did you find the issue in your code and can we close this @RPiAwesomeness ?

**Comment by RPiAwesomeness** [comment]
@wwwdata Oh, yes. My bad!
