### ISSUE TITLE
Make it possible to implement only a subset of the CRUD interface

### ISSUE THREAD

**Issue by freshtonic** [manyminds/api2go#267]
Not all HTTP verbs and routes are relevant to all resources.

If I submit a PR for an alternative `addResource` function that introspects the resource for a subset if the `CRUD` methods and generates only the corresponding routes is this something that could be merged?  I'm happy to do the work.

**Comment by wwwdata** [comment]
Hi. Of course that would be a nice feature.

**Comment by timbunce** [comment]
Any news on this @freshtonic?

**Comment by philippecarle** [comment]
That would be a great feature. 👍
But imho it would introduce a huge BC break and so it definitely needs to be developed and merged before 1.0.

**Comment by philippecarle** [comment]
+ i would be up to work on that but being a quite new gopher, I think it'd be safer if i got some advice on how it should be implemented. A new `Operations` interface with a getter returning a slice of string (defined in constants) ?

**Comment by wwwdata** [comment]
@philippecarle I guess the best way to split up the CRUD Operations is to split up the CRUD interface into smaller ones. So one Interface for each method. The API then has to check what interfaces are implemented and only then provides the endpoints that are really needed.

**Comment by wwwdata** [comment]
This could also be done in a backwards compatible way. The CRUD interface can stay the same and consists of all the individual ones.

```go
type FindOne interface {
	FindOne(ID string, req Request) (Responder, error)
}

type CRUD interface {
	FindOne
	Create
	Delete
	Update
}
```

maybe with different interface names.

**Comment by philippecarle** [comment]
I like this last option. I will probably dig into the code later in the day to find out how hard (or easy) it would be to make this work (and most of all how to update the tests to cover that).

**Comment by freshtonic** [comment]
@timbunce I still think this would be a great feature but I'm no longer involved with the project that would have benefited from this and I no longer have the time to contribute.

All the best!
