### ISSUE TITLE
Adapter to Iris Framework

### ISSUE THREAD

**Issue by fhals** [manyminds/api2go#276]
Is there any way to connect api2go to [iris](https://github.com/kataras/iris)?

**Comment by wwwdata** [comment]
Do you want to look at iris and if it's possible? Writing a connector is easy and straight forward. You can look at another one as an example.

**Comment by sharpner** [comment]
since iris uses a copy pasted version of julienschmidts router, I think it should be possible, but never tried it ;)

**Comment by wwwdata** [comment]
I am currently looking into it. It's possible. Will do a PR for @fhals to test when I'm done

**Comment by wwwdata** [comment]
Currently thinking about fasthttp. They use that instead of the standard net.http package from go and it's not compatible per default. We will have to work around that. That's the main part of the adapter

**Comment by wwwdata** [comment]
So after really looking into it: the main issue is to make api2go fasthttp compatible to also support iris afaik

**Comment by wwwdata** [comment]
https://godoc.org/github.com/valyala/fasthttp/fasthttpadaptor is also an option, but I guess this kills the performance when we convert the net/http stuff to fasthttp for every request. So the only good solution would be a api2go fasthttp compatible version

**Comment by fhals** [comment]
Yes, I do agree. Connecting to fasthttp would be better.  And I just know that there is controversy with author of Iris, so actually more people will use other framework such as [echo](https://github.com/labstack/echo)
