### ISSUE TITLE
question: toOne

### ISSUE THREAD

**Issue by dalu** [manyminds/api2go#282]
my javababble and sql relationship terminology is a bit rusty as I've just worked with mongo for a while.
So I have a question about those relationships and an example.

I'm trying to write a simple testprogram using api2go.

The models look like:
```go
type Post struct {
	ID    string `bson:"_id" json:"id"`
	Title string `bson:"title" json:"title"`
	Text  string `bson:"text" json:"text"`
}

func (p *Post) SetID(string) error {
	panic("implement me")
}

func (p Post) GetID() string {
	panic("implement me")
}

type Comment struct {
	ID     string `bson:"_id" json:"id"`
	PostID string `bson:"post_id" json:"post_id"`
	Author string `bson:"author" json:"author"`
	Text   string `bson:"text" json:"text"`
}
```

So I have a PostID field on the Comment struct.
I do **not** want to have a commentIDs slice on the Post struct.
Is this possible with api2go? Which interfaces do I have to implement and where?

Also in the example app with user and chocolate, there's
```go
func (u User) GetID() string {}
func (u *User) SetID(string) error {}
```
The SetID func has a pointer to User, but the GetID func doesn't.
Why is that, or rather can I just make all methods refer to a *Post/*User instead of this pointer no-pointer thing?

**Comment by wwwdata** [comment]
Hi, the `SetID` method has a pointer because we write the ID into the `User` struct. Otherwise this would not be possible. And yes it's  up to you if you want to use pointers everywhere or not.

You also don't need to have commentIDs in the Post struct. It's up to you how you manage that. You just need to implement the interface methods that will be called by the marshaler to determine whether there are references, reference IDs that need to be included or whole structs that need to be embedded. See: https://github.com/manyminds/api2go#marshalling-with-references-to-other-structs

**Comment by dalu** [comment]
Thanks for feedback,
is this a toOne relationship in the Comment?
This ManyToOne OneToMany ManyToMany terminology is so confusing.
In my mind I know, Comment is associated with Post and therefore needs to have a PostID somewhere.
So when I'd like to find all comments associated with that post I just query comments by postId.
But I don't know when to say OneToMany or ManyToOne.
When using jsonapi.RelationshipType, does the
jsonapi.ToOneRelationship express that, in this case Comment has exactly 1 Post, because there is only 1 PostID stored in Comment?
And if I added a slice of CommentIDs in Post, would that be seen as a jsonapi.ToManyRelationship?

Anyhow I'm not sure what to fill the fields with
```go
package model

import "github.com/manyminds/api2go/jsonapi"

type Post struct {
	ID    string `bson:"_id" json:"id"`
	Title string `bson:"title" json:"title"`
	Text  string `bson:"text" json:"text"`
}

func (p *Post) SetID(id string) error {
	p.ID = id
	return nil
}

func (p *Post) GetID() string {
	return p.ID
}

type Comment struct {
	ID     string `bson:"_id" json:"id"`
	PostID string `bson:"post_id" json:"post_id"`
	Author string `bson:"author" json:"author"`
	Text   string `bson:"text" json:"text"`
}

func (c *Comment) GetReferences() []jsonapi.Reference {
	return []jsonapi.Reference{{Type: "post", Name: "post", Relationship: jsonapi.ToOneRelationship, IsNotLoaded: true}}
}

func (c *Comment) GetID() string {
	return c.ID
}

func (c *Comment) GetReferencedIDs() []jsonapi.ReferenceID {
	return []jsonapi.ReferenceID{{ID: c.PostID, Type: "post", Name: "post", Relationship: jsonapi.ToOneRelationship}}
}
```

Or what do Type and Name need to be set to?
And seeing this I'd probably like to have references to posts when querying posts over http.

**Comment by dalu** [comment]
Ah well, I went further along and I have to create a Responder and it's all just too much additional work to get things done. Still thanks for feedback.

Maybe some automation via struct field tags would help simplify the workflow.
