### ISSUE TITLE
Get key from QueryParams filter

### ISSUE THREAD

**Issue by irene-m** [manyminds/api2go#289]
I need to get a key from QueryParams filter. 
For example I have: users?filter[id]=2, but would also like to leave option for it to be filter[name]=John.

So I would like to have option to get whether it is id or name inside filter. As far as I can see there is no implemented possibility for that, except for me to write code that would take what is in that string, inside those brackets. 

Or is there?

**Comment by wwwdata** [comment]
You get an instance of `api2go.Request` in your resources. This has `QueryParams` and `PlainRequest` which is the standard go `Request` object. You should be able to get out everything with that. Inside the standard `Request` instance you can access the `URL` struct that provides you with everything, see: https://godoc.org/net/http#Request

**Comment by irene-m** [comment]
I tried with PlainRequest. I have done this: r.PlainRequest.URL.Query. And I got:
` map[filter[id]:[2] filter[name]:[John]]`
Key filter[id] is still string. I need to get x from filter[x].

**Comment by sharpner** [comment]
This might be a generic go problem and has nothing to do with api2go. You should take a look at the [URL](https://golang.org/pkg/net/url/#URL.Query) struct. 

If that's not enough maybe this helps?
https://stackoverflow.com/questions/15407719/in-gos-http-package-how-do-i-get-the-query-string-on-a-post-request

**Comment by irene-m** [comment]
You're probably right. 

I am trying to follow JSON API specifications everywhere I can and well I can easily solve this problem by using for example users?id=2&name=John OR checking in code each filter, but the first one isn't the right way to go if we want to follow JSON API specification, since it said that filter keyword must be used[( http://jsonapi.org/format/#fetching-filtering)].

I looked and tried almost everything, but the key is always the whole filter[x] and it is string, so can't do anything with it. The key should be x if this filter keyword is used if you ask me. Do you agree?

**Comment by wwwdata** [comment]
@irene-m so you want a query parameter `filter` that is used as an array, right? so you have: `url/?filter[id]=foo&filter[name]=bar`

Unfortunately that is how this works in go. So all query parameters even with the array brackets are a string and you need to manually parse them like I did here for example: https://github.com/manyminds/api2go/blob/b893b9448d075a17008d94413004e337705bb212/api.go#L50-L54

and nice btw that embedding code finally works, thanks Github Devs 😄

**Comment by irene-m** [comment]
I just wanted to see if it is possible in some other way. Since it is not, gotta do it that way. 

Thanks for all the answers and help. :)
