### ISSUE TITLE
Error log / stack trace support

### ISSUE THREAD

**Issue by Azuka** [manyminds/api2go#297]
I wasn't sure if this was covered / implemented here but is there support for passing in a logger (e.g. for StackDriver, or logrus) or some interface with method `Error(error)` so we can log stack traces of errors that happen inside a resource?

**Comment by sharpner** [comment]
I am not quite sure what exactly you mean. 

Nothing currently prevents you from logging anything. You could for example wrap the api2go.handler which you register at the http.Server and log every request... Maybe you could specify what exactly you want to achieve?

**Comment by Azuka** [comment]
Thanks @sharpner.

I was looking to see if any errors caught by the [handleError()](https://github.com/manyminds/api2go/blob/b893b9448d075a17008d94413004e337705bb212/api.go#L1148) method could potentially be logged especially when triggered from inside the `api2go` package itself.

**Comment by sharpner** [comment]
well we currently log at this exact position with the std log package. So you could already redirect using [log.SetOutput](https://golang.org/pkg/log/#SetOutput) to redirect anywhere you like. Is that sufficient?

**Comment by Azuka** [comment]
@sharpner, that should work. I'm using logrus (which can act as an io.Writer) with hooks. I'll try setting that and let you know if it works.

**Comment by sharpner** [comment]
I'm closing this for now,  just reopen if this issue has not been solved for you :)
