### ISSUE TITLE
SetToOneReferenceID called with wrong name when multiple foreign keys to same type

### ISSUE THREAD

**Issue by drauschenbach** [manyminds/api2go#312]
I have a model with multiple foreign key references to the same remote reference.

```go
type Person struct {
   ID string `json:"-"`
   ActiveCommentIDs []string `json:"-"`
   DeletedCommentIDs []string `json:"-"`
}

func (self Person) GetReferences() []jsonapi.Reference {
   result := []jsonapi.Reference{
      jsonapi.Reference{Type: "comments", Name: "active-comments", IsNotLoaded: true, Relationship: jsonapi.ToManyRelationship},
      jsonapi.Reference{Type: "comments", Name: "deleted-comments", IsNotLoaded: true, Relationship: jsonapi.ToManyRelationship},
   }
}

func (self Person) GetReferencedIDs() []jsonapi.ReferenceID {
   result := []jsonapi.ReferenceID{}
   for _, commentID := range self.ActiveCommentIDs {
      referenceID := jsonapi.ReferenceID{Type: "comments", Name: "active-comments", ID: commentID, Relationship: jsonapi.ToManyRelationship}
      result = append(result, referenceID)
   }
   for _, commentID := range self.DeletedCommentIDs {
      referenceID := jsonapi.ReferenceID{Type: "comments", Name: "deleted-comments", ID: commentID, Relationship: jsonapi.ToManyRelationship}
      result = append(result, referenceID)
   }
   return result
}

func (self *Person) SetToManyReferenceIDs(name string, ids []string) error {
   if name == "active-comments" {
      self.ActiveCommentIDs = ids
   } else if name == "deleted-comments" {
      self.DeletedCommentIDs = ids
   } else {
      return errors.New("unknown relation")
   }
   return nil
}

func (self *Person) SetToOneReferenceID(name, id string) error {
   // HACK: api2go requires and calls SetToOneReferenceID for to-many relations
   return self.SetToManyReferenceID(name, []string{id})
}
```

When I create the following struct, it marshals OK and has perfect JSON content:

```
person := model.Person{ID: "23", ActiveCommentIDs: []string{"123"}}
```

And I can unmarshal it in a unit test and the content is still a perfect match.

But when I POST it through REST, and when it is unmarshalled before being passed to a Resource Create() function, the relations get mixed and the wrong one gets called. My `SetToOneReferenceID()` function gets called with `name = "deleted-comments"`.

I think there is a relation mapper that is looking for the first match for a given Type name, instead of searching by relation name. Which prevents 2 or more foreign keys from being used in a struct to point to the same remote resource.

**Comment by drauschenbach** [comment]
I've isolated this problem. I am using `jsonapi.Marshal` to generate JSONAPI style of JSON that I am POSTing via REST. Marshal collapses `"data":[]` elements.

However, on the receiving end, JSONAPI has a malfunction when these nested data elements are not present.

So back to my example above, I had to modify the POSTed json to replace `"deleted-comments": {}` with `"deleted-comments: {"data":[]}`. And that then allowed the other relations to get processed.

Another work-around a colleague of mine just found is to selectively publish a different schema if no foreign key values exist. But the client then loses the ability to see the schema, to know how to offer create options for related data, which is not exactly in the spirit of JSONAPI links.

**Comment by drauschenbach** [comment]
Fixed by setting Reference `IsNotLoaded: false`.

**Comment by wwwdata** [comment]
Hm, we should definitly look further into this and at least add a test case to our unit tests to make sure this works.

Can you paste some example jsons that you also tried it out with as a reference as well? Thanks so far already!

**Comment by drauschenbach** [comment]
Given that `IsNotLoaded` fixed my issue, and is the thing that drives omission of the `"data":[]` element, I think this is not a bug.
