### ISSUE TITLE
Errors from SetToOneReferenceID and SetToManyReferenceIDs are ignored

### ISSUE THREAD

**Issue by velovix** [manyminds/api2go#328]
The SetToOneReferenceID and SetToManyReferenceIDs methods are defined as returning an error value, but that value is ignored in the places they are called. If these errors were to simply propagate up the stack to the Marshal and Unmarshal calls, I think that would be sufficient.

**Comment by wwwdata** [comment]
Would you like to fix this and open a PR?

**Comment by velovix** [comment]
I'd be happy to! I'll see what I can do.

**Comment by velovix** [comment]
Resolved by #329
