### ISSUE TITLE
Custom Resource endpoints?

### ISSUE THREAD

**Issue by stobias123** [manyminds/api2go#344]
I have a resource, `users` that gets registered and served as shown.

Register
```golang
	api.AddResource(model.User{}, resource.UserResource{ UserStorage: userStorage })
```

Server output
```
[GIN-debug] OPTIONS /api/v2/users/:id         --> github.com/manyminds/api2go/routing.ginRouter.Handle.func1 (3 handlers)
[GIN-debug] GET    /api/v2/users/:id         --> github.com/manyminds/api2go/routing.ginRouter.Handle.func1 (3 handlers)
```

Is there any way I can get this resource to be served from `/api/v2/account` instead of `users`?

**Comment by sharpner** [comment]
Yes, you can implement this interface: https://github.com/manyminds/api2go#entitynamer
